-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jul 26, 2023 at 07:13 PM
-- Server version: 10.4.22-MariaDB
-- PHP Version: 8.1.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `produk`
--

-- --------------------------------------------------------

--
-- Table structure for table `keranjang`
--

CREATE TABLE `keranjang` (
  `id_keranjang` int(11) NOT NULL,
  `id_user` int(11) NOT NULL,
  `id_produk` int(11) NOT NULL,
  `jumlah` int(11) NOT NULL,
  `tanggal_pesan` datetime NOT NULL,
  `catatan` varchar(255) NOT NULL,
  `checked` varchar(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `keranjang`
--

INSERT INTO `keranjang` (`id_keranjang`, `id_user`, `id_produk`, `jumlah`, `tanggal_pesan`, `catatan`, `checked`) VALUES
(1, 5, 76, 7, '2023-07-16 08:13:12', 'aaa', 'checked'),
(2, 5, 19, 5, '2023-07-16 08:13:51', 'bbb', 'checked'),
(3, 5, 29, 10, '2023-07-16 08:15:22', 'ccc', 'checked'),
(4, 5, 46, 5, '2023-07-16 09:30:40', 'ddd', 'checked'),
(5, 5, 76, 4, '2023-07-16 10:30:08', 'eee', 'checked'),
(6, 5, 76, 5, '2023-07-16 10:44:37', 'fff', 'checked'),
(7, 1, 52, 10, '2023-07-16 12:26:15', 'a', 'checked'),
(8, 1, 58, 1, '2023-07-16 14:32:49', 'a', 'checked'),
(9, 4, 44, 5, '2023-07-16 20:37:01', 'a', 'checked'),
(10, 4, 59, 2, '2023-07-16 20:37:53', 'a', 'checked'),
(11, 4, 50, 3, '2023-07-16 20:41:02', 'a', 'checked'),
(12, 4, 40, 2, '2023-07-16 20:41:36', 'a', 'checked');

-- --------------------------------------------------------

--
-- Table structure for table `produk`
--

CREATE TABLE `produk` (
  `id` int(11) NOT NULL,
  `nama` varchar(255) DEFAULT NULL,
  `harga` int(11) DEFAULT NULL,
  `deskripsi` longtext DEFAULT NULL,
  `file` varchar(255) DEFAULT NULL,
  `kategori` varchar(255) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Dumping data for table `produk`
--

INSERT INTO `produk` (`id`, `nama`, `harga`, `deskripsi`, `file`, `kategori`) VALUES
(80, 'aaaa', 35336, '<span style=\"font-family:Georgia,serif\"><strong><span style=\"color:#2980b9\"><span style=\"font-size:72px\"><span style=\"background-color:#f1c40f\">ghfhhd</span></span></span></strong></span>', '20230712003213.jpg', 'minuman'),
(13, 'Coklat Yosan Choyo Choyo / makanan jadul / coklat jadul /cemilan jadul', 11000, '<h2><span style=\"font-family:Comic Sans MS,cursive\"><strong><em><span style=\"background-color:#ffff99\">Kondisi: Baru</span><br />\r\n<span style=\"background-color:#ffff99\">Min. Pemesanan: 1 Buah</span><br />\r\n<span style=\"background-color:#ffff99\">Etalase: Semua Etalase</span><br />\r\n<span style=\"background-color:#ffff99\">Choyo Choyo merupakan coklat jadul yang di produksi oleh Yosan,,, kangen dengan coklat ini ? yuk di order</span><br />\r\n<span style=\"background-color:#ffff99\">cocok untuk teman cemilan anda</span><br />\r\n<br />\r\n<span style=\"background-color:#ffff99\">Isi 20 pcs plus bonus 1</span><br />\r\n<br />\r\n<span style=\"background-color:#ffff99\">#makananjadul #coklat</span></em></strong></span></h2>\r\n', '13.jpg', 'minuman'),
(14, 'Permen Jahe Spesial 61 125gr/Permen/Makanan Ringan/Camilan/Candy', 5700, 'Kondisi: Baru<br />\r\nMin. Pemesanan: 1 Buah<br />\r\nEtalase: Permen<br />\r\nUntuk mengurangi resiko pembatalan, sebelum order mohon menanyakan stok terlebih dahulu.<br />\r\n<br />\r\nPacking sesuai standar pengiriman<br />\r\nTidak menerima refund/tukar barang<br />\r\n*Pembayaran setelah pk 14.00 WIB dikirim hari berikutnya<br />\r\nBuka Senin-Sabtu pukul 08.00-17.00 WIB (Minggu Libur)<br />\r\n<br />\r\nPermen Jahe Special 61 125gr<br />\r\nPermen jahe alami dengan rasa segar<br />\r\n<br />\r\n#permen #makanan #kembanggula #camilan #candy', '14.jpg', 'makanan'),
(15, 'SNACK SABENA STIK KERIPIK MAKANAN RINGAN ANEKA RASA KEJU BALADO JAGUNG', 12999, 'SABENA KERIPIK STIK<br />\r\n<br />\r\nSTIK SABENA MURAH<br />\r\n<br />\r\nCEMILAN<br />\r\n<br />\r\nSNACK<br />\r\n<br />\r\nJAJANAN<br />\r\n<br />\r\nStik Sabena<br />\r\n<br />\r\nLagi nyari cemilan atau snack buat rame rame tapi duit di kantong pas pasan snack sabena ini pilihan yang tepat,dengan pilihan rasa yang lengkap serta rasanya pun nendang banget bikin nongkrong atau kongkow kamu makin asiikkk<br />\r\n<br />\r\n<br />\r\nTersedia 5 variant rasa<br />\r\nAda rasa baru ya..????<br />\r\n- Balado<br />\r\n- Keju<br />\r\n- jagung bakar<br />\r\n- Sapi panggang<br />\r\n- Kari ayam<br />\r\nnetto : 360gr<br />\r\nJangan tunggu kehabisan<br />\r\n<br />\r\nHARGA YANG TERTERA ADALAH HARGA 1 PACK<br />\r\nYukk cus di order....', '15.jpg', 'makanan'),
(16, 'Proffle High Protein Waffle (1 pc)', 23500, 'Kondisi: Baru<br />\r\nMin. Pemesanan: 1 Buah<br />\r\nEtalase: PROFFLE X FASTBITE<br />\r\nBiskuit waffle renyah pertama di Indonesia yang mengandung tinggi protein dan bisa isi kembali energimu. Cocok buat kamu yang mau jaga pola hidup sehat saat New Normal ini.<br />\r\n<br />\r\nTersedia dalam 4 varian rasa: Mentega, Cokelat, Sapi Panggang dan Kopi.<br />\r\nSudah tersertifikasi oleh BPOM RI dan Halal.', '16.jpg', 'makanan'),
(17, 'Marin Food Candy Cheese Almond / Permen Keju Almond / Permen Jepang', 28300, '<strong><span style=\"font-family:Courier New,Courier,monospace\"><span style=\"font-size:14px\">Kondisi: Baru<br />\r\nMin. Pemesanan: 1 Buah<br />\r\nEtalase: Candy atau Permen<br />\r\nProduct of Japan<br />\r\n<br />\r\nisi 24 gram<br />\r\n<br />\r\nIngredients: Natural cheese, Almond / Emulsifier (Phosphates), flavor<br />\r\n<br />\r\nExp 2022<br />\r\n<br />\r\nPerpaduan rasa Keju dan Almond dijadikan sebuah permen yang membuat rasa unik!!!<br />\r\n<br />\r\nIt is candy-shaped cheese with which you can enjoy the flavor and texture of grated roasted almonds and perfect for snacks.<br />\r\nIt is bite-sized and conveniently packaged.</span></span></strong>', '17.jpg', 'makanan'),
(18, 'Momogi Stick Snack Makanan Ringan 12gr - Coklat [1 Box @ 10 Pcs]', 10000, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Momogi Stick\r\nWAJIB PEMBELIAN KARDUS JIKA ORDER MAU DIKIRIMKAN DENGAN PACKING KARDUS.\r\n\r\nMomogi Stick Snack Makanan Kering 12gr [1 Box @ 10 Pcs]\r\n\r\nRasa: COKLAT / CHOCOLATE\r\n\r\nMomogi Stick adalah makanan ringan berbentuk stick dan berongga di bagian tengah dengan berbagai pilihan rasa. Mempunyai kemasan yang simple sehingga mudah dibawa kemana - mana. Jajanan/Snack kesukaan anak-anak dan orang dewasa dan ideal untuk dikonsumsi bersama keluarga.\r\n\r\nBPOM RI MD 273710098182', '18.jpg', 'makanan'),
(19, '50 Pcs - Dimsum Siomay Premium Super Grosir Frozen Food Halal', 100625, '<span style=\"color:#e74c3c\">Kondisi: Baru<br />\r\nMin. Pemesanan: 1 Buah<br />\r\nEtalase: Semua Etalase<br />\r\nYang pengen buka usaha tapi masih bingung mau usaha apa</span><br />\r\n<br />\r\n<span style=\"color:#27ae60\">SmallFood Dimsum Premium pilihan tepat untuk JUALAN atau bisa juga untuk konsumsi sendiri bareng keluarga, atau untuk acara arisan, kawinan, hajatan, sunatan, pengajian, terserah lah mau buat acara apa aja :D<br />\r\n<br />\r\nKalo Kamu punya usaha catering juga bisa ditambahin ke menunya biar lebih variatif supaya klienya tidak bosan.</span><br />\r\n<br />\r\n<span style=\"color:#f39c12\">Isi : 50 Pcs<br />\r\n1 paket sudah MIX/CAMPUR 5 varian toping udang, beef, tuna, jamur, dan wortel</span><br />\r\n<br />\r\nHarganya murah,<br />\r\nAnda bisa jual 2.500/pcs atau 3.000/pcs untuk harga kaki lima<br />\r\natau bisa jual 7.000/pcs kalau jualan di bazar Mall, Bisa hitung sendiri berapa hasilnya :D<br />\r\n<br />\r\nKok harganya murah sih?<br />\r\nKarna kami produksi sendiri, jadi bisa lebih murah<br />\r\n<br />\r\nGimana...?<br />\r\nDengan modal MURAH anda dapat untung WAH<br />\r\n<br />\r\nKenapa sih harus Dimsum Smallfood?<br />\r\nkan Dimsum yg lainya banyak?<br />\r\nKami tidak mengklaim bahwa produk kami yg paling baik, biar review yang berbicara<br />\r\ndan kamu bisa coba sendiri sensasi rasa nya<br />\r\n<br />\r\nDimsum Smallfood menggunakan kualitas bahan premium filet dada ayam segar pilihan<br />\r\ndengan komposisi daging 80%<br />\r\nsehingga menciptakan cita rasa yang nendang di mulut dan tekstur yg lembut di setiap gigitan nya<br />\r\n<br />\r\nUkuranya juga lumayan gede dijamin kenyang n puas deh<br />\r\n<br />\r\n<br />\r\nDapet sausnya gak?<br />\r\nDapet dong, GRATIS !!<br />\r\n<br />\r\nOiya, dimsum Smallfood Halal gak?<br />\r\nUntuk sertifikat halal MUI kami belum ada, tapi dari bahan dan cara pengolahan InsyaAllah halal kak<br />\r\n<br />\r\nBisa disimpan berapa lama?<br />\r\nKalau beku di freezer bisa tahan sampai 1 bulan<br />\r\nkalau taruh di kulkas biasa paling lama 7 hari<br />\r\nkalau di suhu ruangan 24 jam saja<br />\r\nkalau di piring, cuma tahan 5 menit<br />\r\n<br />\r\nAyo... Buruan diorder... Dijamin Puwaassss ....', '19.jpg', 'makanan'),
(20, 'Keripik Buah dan Sayur Mix Khas Malang Panji Food 65-100gr', 16850, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Snack Viral\r\nInfo jadwal pengiriman & Kebijakan toko:\r\nPengiriman senin-sabtu (Minggu tidak ada pengiriman) mulai pk 11.00 WIB, orderan yang masuk diatas pk 16.00 WIB akan masuk pengiriman besok pagi nya\r\nPengemasan paket menggunakan kardus/bubble akan disesuaikan dengan jumlah pesanan\r\nInfo reseller, silahkan chat admin\r\n\r\nUntuk komplain barang kurang/tidak sesuai deskripsi silahkan infokan ke admin kami sertakan video unboxing, admin kami siap membantu\r\n\r\nREADY STOCK!\r\nDistributor tangan pertama\r\nSelama barang masih ada di etalase berarti stock masih ada dan bisa dipesan\r\n\r\nKETERANGAN DAN SPESIFIKASI PRODUK:\r\nAneka keripik buah dan sayur khas kota Malang dari Panji Food ini terbuat dari buah buahan segar, bentuknya besar-besar yah bukan potongan yang kecil, renyah, kualitas ekspor\r\n\r\nTersedia varian rasa, silahkan pilih sbb:\r\n1. Keripik Nangka 100gr\r\n2. Keripik Nangka 65gr\r\n3. Keripik Salak 65gr\r\n4. Keripik Apel 65gr\r\n5. Keripik Sayur mix 100gr\r\n6. Keripik Sayur Mix 65gr\r\n\r\nSertifikasi:`\r\nHalal\r\n\r\nBerat Netto 65-100gr\r\n\r\nPaket 1kg: 5-6pack\r\n\r\nMasa exp dan saran penyimpanan:\r\nMasa exp tahan 12 bulan dalam suhu ruang, selama kemasan belum dibuka', '20.jpg', 'makanan'),
(21, 'Sushi Nori Rumput Laut Lembar Roasted Panggang Java Super Food', 18500, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Lainnya\r\nSUSHI NORI JAVA SUPER FOOD ROASTED SEAWEED RUMPUT LAUT\r\nNetto. 50gr\r\n\r\nDetail:\r\n- Sushi nori\r\n- Rasa tawar (Original)\r\n- Sudah dipanggang (ROASTED)\r\n- Lembaran tebal & bisa langsung di makan\r\n- HALAL MUI\r\n\r\nNori Adalah nama dalam bahasa Jepang untuk bahan makanan berupa lembaran rumput laut yang dikeringkan. Nori digunakan sebagai hiasan dan penyedap berbagai macam masakan Jepang, lauk sewaktu makan nasi, dan bahan makanan ringan seperti senbei. Bahan baku adalah alga jenis Porphyra seperti Porphyra pseudolinearis Ueda yang dikenal sebagai Iwanori dan Porphyra yezoensis Ueda.\r\n\r\nWalaupun warna tidak dapat dijadikan pegangan kualitas, lembaran nori berkualitas tinggi umumnya berwarna hitam kehijauan, sedangkan nori berkualitas lebih rendah berwarna hijau hingga hijau muda.\r\n\r\nSushi Nori Roasted Seaweed Rumput Laut Adalah rumput laut dengan rasa original yang telah memiliki sertifikat Halal MUI, sehingga aman dikonsumsi secara langsung. Ideal dijadikan sebagai pelengkap makanan sushi.', '21.jpg', 'minuman'),
(22, 'Sambosa Daging Samosa Beef Samosa Daging Per Pak / Sambosa Frozen Food', 50900, 'Kondisi: Baru<br />\r\nMin. Pemesanan: 1 Buah<br />\r\nEtalase: FrozenCampuz<br />\r\nâ–¶ Halo, Welcome to FrozenCampuz - Delicious Food Carrying Happiness<br />\r\n<br />\r\nAneka Frozen Food Homemade dan Higienis<br />\r\nCITA RASA KHAS KOTA SURABAYA<br />\r\nAman Dikonsumsi Keluarga dan Anak - Anak<br />\r\nHALAL, NO MSG, NO PRESERVATIVE<br />\r\nSehat, Lezat, Gurih, Bergizi Tinggi<br />\r\n<br />\r\nâ–¶ SAMOSA DAGING BY FROZENCAMPUZ<br />\r\nSamosa yang didalam isinya full daging. Rasa lezat dan gurih. Cita rasa khas Kota Surabaya. Isi 10 pcs/pak. Berat per pak 700 gram. Kondisi produk beku. Cara penyajiannya digoreng dengan minyak panas. Nikmat dikonsumsi dengan saus, cabai, dll.<br />\r\n<br />\r\nâ–¶ NOTES<br />\r\nProduk ini aman/tahan hingga 30 hari jika disimpan didalam freezer<br />\r\nProduk ini rentan/cenderung cepat berubah rasa, kondisi, dll (tidak awet) di suhu ruang/chiller<br />\r\nProses pengiriman dan penyimpanan sangat berpengaruh terhadap kualitas produk sehingga,<br />\r\n<br />\r\nâ–ªï¸ SETELAH SAMPAI TUJUAN, mohon simpan langsung frozen kedalam FREEZER<br />\r\n<br />\r\nâ–ªï¸ SANGAT DISARANKAN untuk pengiriman JABODETABEK =&gt; GOSEND/GRAB EXPRESS/ANTERAJA SAMEDAY ATAUPUN INSTANT<br />\r\n<br />\r\nâ–ªï¸ SANGAT DISARANKAN untuk pengiriman LUAR JABODETABEK/KOTA/PULAU =&gt; PAXEL NEXT DAY/JNE YES<br />\r\n<br />\r\nâ–ªï¸ Keterlambatan/Kerusakan paket saat sudah di ekspedisi di luar tanggung jawab kami/seller/toko, Dikirim oleh kami dengan kondisi baik dan fresh, Mohon pertimbangkan jasa pengiriman yang dipilih<br />\r\n<br />\r\nâ–¶ KAMI MENJUAL ANEKA FROZEN BEKU<br />\r\nAneka Risoles, Samosa, Pastel, Kroket, Kebab, Martabak, Sosis Solo, Lumpia, Dimsum, Siomay, Bakso, Pizza, Onde-Onde, Roti Maryam, Donat, Roti Bakery, dll<br />\r\n<br />\r\nâ–ªï¸ MENERIMA PESANAN CAFE, KANTOR, RESTORAN, CATERING, KAMPUS, WISUDA, WEDDING, HAJATAN, DAN EVENT LAINNYA<br />\r\n<br />\r\nâ–ªï¸ Untuk pemesanan frozen food dalam jumlah besar dimohon chat/call/wa pada nomor yang tercantum pada profil toko kami dan mohon kesediannya menunggu respon paling lambat 1x24 jam terutama pada masa sibuk weekdays/weekend ????<br />\r\n<br />\r\nTerima Kasih', '22.jpg', 'makanan'),
(23, 'Tes Stik Balado 225 gr (Ace Food) Stik Balado Tes', 12000, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Aneka Biskuit dan Snack\r\nTes Stik Balado 220gr (Ace Food) Stik Balado Tes\r\nStock selalu baru!!\r\n\r\nStik Balado TES dari Ace Food, stik ekstrudat jagung rasa sambal balado.\r\nNetto 220 gram. Kena berat volume ya, harap maklum :)\r\n\r\n\r\nBisa dengan Go Send', '23.jpg', 'makanan'),
(24, 'Makanan Ringan Kenbi 777 Keripik Kentang Ebi RACIKAN UDANG KERING', 68999, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Semua Etalase\r\nKENBI 777 merupakanKeripik kentang dengan perpaduanudang keringdan kentang pilihan\r\n\r\nKentang Ebi | Keripik kentang dengan racikan udang kering pilihan berkualitas tinggi. Lezat dan bergizi .\r\n\r\nMudah dibawa, Simple, Praktis, Lezat dan Higiens.\r\n\r\nDengan kemasan cantik dan mungil . KENBI 777 merupakan keripik kentang dengan racikan udang kering (ebi) pilihan ini cocok untuk dijadikan cemilan. tambahan lauk pauk atau dimakan dengan mie. bubur. atau hidangan lainnya .\r\n\r\nKomposisi:\r\nKentang asli berkualitas pilihan\r\nEbi (udang kering) asli berkualitas tinggi\r\nBawang merah\r\nGaram\r\nCabai Merah\r\nGula\r\nBumbu racikan khusus\r\nTanpa Bahan Pengawet dan Tanpa MSC\r\nDikemas dengan Higenis Kemasan DISEGELdengan Baik untuk menjaga MUTU dan KWALITAS\r\n\r\nAsli produk dalam negeri yang terdaftar resmi\r\nDIJAMIN 100% HALAL\r\nBobot bersih kentang ebi 180 gram (netto)\r\nBobot Pengiriman 350 gram\r\nP-IRT No.215367101016619', '24.jpg', 'makanan'),
(25, '[OPENING PROMO] Dimsum Siomay Ayam Frozen Food Dim Sum 50 PCS', 85050, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Semua Etalase\r\nHi Kak WAJIB Baca keterangan ya kak :)\r\n\r\nTersedia berbagai toping! Boleh pilih salah satu / mix ya..\r\n- Original ( topping wortel )\r\n- Crab stick\r\n- Jamur\r\n- Smoked Beef\r\n- Cheese\r\n- Mix\r\n\r\nAye dimsum adalah pabrik dimsum berkhualitas.\r\n- menggunakan bahan-bahan premium\r\n- rasa bisa diadu\r\n- yang pasti HALAL dan tidak menggunakan MSG\r\n- READY STOCK ya kak tidak perlu ditanyakan lagi ketersediaannya..\r\n\r\nBagi yang mau jadi reseller / distributor boleh banget! bisa langsung contact admin di inbox aja ya\r\n\r\nProduk ini ready untuk Instant, Sameday dan Next Day.\r\n----------------------------------------------------------------------------------------\r\n\r\nYuk dicoba ya kak! Dijamin NAGIH ~\r\nLihat Lebih Sedikit', '25.jpg', 'minuman'),
(26, 'Makanan Ringan Khas Purwakarta Simping Kaum \"M2N\" Boga Rasa', 15000, 'Kondisi: Baru\r\nMin. Pemesanan: 5 Buah\r\nEtalase: Makanan Ringan\r\nSimping merupakan salah satu produk dari toko kami dengan berbagai varian rasa dan harga terjangkau. Varian rasa:\r\n- Kencur\r\n- Keju\r\n- Cabai\r\n- Nangka\r\n- Strawberry\r\n- Pandan\r\n- Coklat\r\n- Durian\r\n- Bawang\r\n\r\nBisa menggunakan dus khas Purwakarta yang bisa dipesan secara terpisah.\r\n\r\nJika Anda ingin memesan, lebih baik cantumkan rasanya di bagian keterangan. Bila tidak, terpaksa kami mengirimkan simping dengan rasa yg RANDOM', '26.jpg', 'minuman'),
(27, 'Samosa Kentang Kari 6pcs Frofoo Halal Homemade Frozen Food', 28000, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Semua Etalase\r\nTerbuat dari kentang yang dihaluskan, ditambah daging giling dengan bumbu kari yang khas. Dibalut dengan kulit lumpia renyah berbentuk segitiga. Praktis tinggal goreng. Homemade, halal, non MSG dan tanpa pengawet. Tersedia isi 8pcs/pack, bukan 15pcs seperti sebelumnya. Ukuran lebih besar dibanding sebelumnya.', '27.jpg', 'minuman'),
(28, 'Bairong Chia Seed Saline Biscuit / biskuit diet / makanan diet / oat', 53500, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Semua Etalase\r\nBairong Chia Seed Saline Biscuit 400gr\r\n\r\nexpired : 12/2023\r\n\r\nMohon selalu ditanyakan stok barang. Karena toko kami selalu mengikuti stok barang di toko offline kami yang setiap saat selalu berubah. Terima kasih.', '28.jpg', 'makanan'),
(29, 'Abe Food Tempy Keripik Tempe 70 Gram Snack Sehat for Kids Healthy', 17999, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Baby Product\r\nUntuk penambahan extra buble Wrap dan Kardus bisa pesan disini :\r\n\r\nhttps://www.tokopedia.com/madegood/kardus-box-besar-kecil\r\nhttps://www.tokopedia.com/madegood/extra-bubble-wrap-packing', '29.jpg', 'makanan'),
(30, 'CAMILAN BASRENG STICK 200GR JAJAN KILO SNACK CEMILAN MAKANAN OLEHOLEH', 12500, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: CAMILAN SNACK\r\n????CHAT Wa.me/628992145999 FAST RESPON\r\n\r\nCamilan\r\n▶Rasa : Pedas, original\r\n▶Berat : 200gr\r\n▶Renyah, gurih, enak\r\n\r\n????STOK SELALU BARU????\r\n????FOTO REALPICT DARI TOKO KITA????\r\n\r\n.\r\n✔Barang mudah hancur, silahkan atc pembelian packing tambahan bubblewrap dan kardus\r\n\r\n✔Barang dikirim dlm kondisi bagus, kami TIDAK GARANSI jika ada kerusakan dari pihak ekspedisi\r\n\r\n✔Order berarti setuju dengan peraturan toko kami\r\n\r\n✔Beri bintang 5 ⭐⭐⭐⭐⭐ jika puas belanja ditoko kami\r\n\r\n#snack #camilan #camilankiloan #snackkiloan #umama #ansania #shinarglamour #azzura #jilbab #saudiacombo #ciput #batik #snack curah #makaroni #blousebatik #segiempat #oleholeh #batikmurah #jajanankiloan #grosir #cemilan #jajan', '30.jpg', 'minuman'),
(31, 'Hakau Udang - Shrimp Dumpling Hakkau Gaozi FROZEN FOOD DIMSUM PREMIUM', 56000, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: PREMIUM PRAKTIS PACK\r\nSuper Premium Praktis Pack :\r\n\r\nHakau Udang - Shrimp Dumpling Hakkau Gaozi FROZEN FOOD DIMSUM PREMIUM\r\nSpesialis dimsum murah tapi enak\r\n\r\nFrozen food\r\nIsi 10 Pcs\r\nOriginil Home made\r\nFree ongkir - bisa COD\r\nHalal MUI - BPOM proses\r\nPerush berpengalaman 10 th\r\n\r\nDimsum PERTAMA yg pakai bahan\r\nAyam muda (lbh empuk dan lezat)\r\n\r\nBENEFIT BELANJA DI TOKO KAMi :\r\n⁃ Produsen (tangan pertama)\r\n⁃ Pastinya lbh murah\r\n⁃ Dijamin stock selalu baru\r\n⁃ Terlengkap varian nya\r\n⁃ Service & kirim fast respon\r\n⁃ Banyak promo & bonus\r\n⁃ Minggu & tgl merah ttp kirim\r\n*Bandingin aja dgn toko lain\r\n\r\nKELEBIHAN DIMSUM MBLEDOS :\r\n⁃ Murah\r\n⁃ Rasa enak\r\n⁃ Dapat banyak\r\n⁃ Besar\r\n⁃ Bahan berkualitas\r\n⁃ Bersih & higienis\r\n⁃ Pakaging bagus, kuat & save\r\n*Ini jelas bukan dimsum pasaran\r\n\r\nBAIK UNTUK :\r\n⁃ Anak-anak\r\n⁃ Remaja\r\n⁃ Dewasa\r\n⁃ Orang tua\r\n\r\nDISARANKAN UNTUK :\r\n⁃ Cemilan nonton tv\r\n⁃ Main game\r\n⁃ Kumpul keluarga\r\n⁃ Kumpul teman, dll.\r\n(Pokok nya segala suasana\r\nbikin lbh seru deh kak)\r\n\r\nPROMO & BONUS :\r\n1. Disc 20%\r\n2. Beli lbh 5 pack dpt pot hrg\r\n4. Bonus supit/chopstick\r\n5. Bonus resep kekinian\r\n*WoW.. bnyk bgt promo & bonus nya\r\nYuk kak segera check out in\r\nJgn smp Kehabisan, krn terbatas !\r\n\r\nKOMPOSISI :\r\nAyam, terigu, sayuran, rempah, garam, bawang putih, minyak wijen\r\n(Semua bhn alami, bersih & sehat)\r\n\r\n~ DIMSUM DI PROSES\r\nMengikuti standar BPOM & MUI\r\njadi garansi aman di konsumsi\r\n~ DIMSUM DI KEMAS\r\nSudah matang & beku ya kak\r\n~ DIMSUM SEBELUM DI KIRIM\r\nTelah melewati standar kuality kontrol & seleksi yg ketat\r\n\r\nSARAN PENYIMPANAN :\r\n> Freezer (Beku) - 18’ = 2 bln\r\n> chiller/kulkas - 4’ = 7 hr\r\n> Suhu ruangan = 2 hr\r\n\r\nSARAN MEMASAK :\r\n> Kukus / Goreng / Grill = 5 - 10 mnt\r\n\r\nORDER & PENGIRIMAN :\r\na. Instan\r\n⁃ Order sebelum jam 15.00 WIB, dikirim di hari yg sama\r\n⁃ Pakai gosend estimasi sampai 1 hingga 2 jam\r\nb. Regular (free ongkir)\r\n⁃ Order sebelum jam 14.30 WIB, dikirim di hari yg sama\r\n⁃ Ekspedisi yg di pakai : J&T dan paxel\r\nc. Bisa kirim ke seluruh wil Indonesia, luar pulau Jawa harap chat CS kami ya kak!', '31.jpg', 'minuman'),
(32, 'Momogi Stick Snack Makanan Ringan 5gr - Keju [1 Box @ 20 Pcs]', 10000, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Momogi Stick\r\nWAJIB PEMBELIAN KARDUS JIKA ORDER MAU DIKIRIMKAN DENGAN PACKING KARDUS.\r\n\r\nMomogi Stick Snack Makanan Kering 5gr [1 Box @ 20 Pcs]\r\nRasa: KEJU / CHEESE\r\n\r\nMomogi Stick adalah makanan ringan berbentuk stick dan berongga di bagian tengah dengan berbagai pilihan rasa. Mempunyai kemasan yang simple sehingga mudah dibawa kemana - mana. Jajanan/Snack kesukaan anak-anak dan orang dewasa dan ideal untuk dikonsumsi bersama keluarga.\r\n\r\nBPOM RI MD 273710096182\r\nSudah Halal MUI', '32.jpg', 'makanan'),
(33, 'Lumpia Kulit Tahu Kembang - Tofu Skin Roll FROZEN FOOD DIMSUM SPESIAL', 37500, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: SUPER SPECIAL PRAKTIS PACK\r\nSuper Spesial Praktis Pack :\r\n\r\nLumpia Kulit Tahu Kembang - Tofu Skin Roll FROZEN FOOD DIMSUM SPESIAL\r\nSpesialis dimsum murah tapi enak\r\n\r\nFrozen food\r\nIsi 10 Pcs\r\nOriginil Home made\r\nFree ongkir - bisa COD\r\nHalal MUI - BPOM proses\r\nPerush berpengalaman 10 th\r\n\r\nDimsum PERTAMA yg pakai bahan\r\nAyam muda (lbh empuk dan lezat)\r\n\r\nBENEFIT BELANJA DI TOKO KAMi :\r\n⁃ Produsen (tangan pertama)\r\n⁃ Pastinya lbh murah\r\n⁃ Dijamin stock selalu baru\r\n⁃ Terlengkap varian nya\r\n⁃ Service & kirim fast respon\r\n⁃ Banyak promo & bonus\r\n⁃ Minggu & tgl merah ttp kirim\r\n*Bandingin aja dgn toko lain\r\n\r\nKELEBIHAN DIMSUM MBLEDOS :\r\n⁃ Murah\r\n⁃ Rasa enak\r\n⁃ Dapat banyak\r\n⁃ Besar\r\n⁃ Bahan berkualitas\r\n⁃ Bersih & higienis\r\n⁃ Pakaging bagus, kuat & save\r\n*Ini jelas bukan dimsum pasaran\r\n\r\nBAIK UNTUK :\r\n⁃ Anak-anak\r\n⁃ Remaja\r\n⁃ Dewasa\r\n⁃ Orang tua\r\n\r\nDISARANKAN UNTUK :\r\n⁃ Cemilan nonton tv\r\n⁃ Main game\r\n⁃ Kumpul keluarga\r\n⁃ Kumpul teman, dll.\r\n(Pokok nya segala suasana\r\nbikin lbh seru deh kak)\r\n\r\nPROMO & BONUS :\r\n1. Disc 20%\r\n2. Beli lbh 5 pack dpt pot hrg\r\n4. Bonus supit/chopstick\r\n5. Bonus resep kekinian\r\n*WoW.. bnyk bgt promo & bonus nya\r\nYuk kak segera check out in\r\nJgn smp Kehabisan, krn terbatas !\r\n\r\nKOMPOSISI :\r\nAyam, terigu, sayuran, rempah, garam, bawang putih, minyak wijen\r\n(Semua bhn alami, bersih & sehat)\r\n\r\n~ DIMSUM DI PROSES\r\nMengikuti standar BPOM & MUI\r\njadi garansi aman di konsumsi\r\n~ DIMSUM DI KEMAS\r\nSudah matang & beku ya kak\r\n~ DIMSUM SEBELUM DI KIRIM\r\nTelah melewati standar kuality kontrol & seleksi yg ketat\r\n\r\nSARAN PENYIMPANAN :\r\n> Freezer (Beku) - 18’ = 2 bln\r\n> chiller/kulkas - 4’ = 7 hr\r\n> Suhu ruangan = 2 hr\r\n\r\nSARAN MEMASAK :\r\n> Kukus / Goreng / Grill = 5 - 10 mnt\r\n\r\nORDER & PENGIRIMAN :\r\na. Instan\r\n⁃ Order sebelum jam 15.00 WIB, dikirim di hari yg sama\r\n⁃ Pakai gosend estimasi sampai 1 hingga 2 jam\r\nb. Regular (free ongkir)\r\n⁃ Order sebelum jam 14.30 WIB, dikirim di hari yg sama\r\n⁃ Ekspedisi yg di pakai : J&T dan paxel\r\nc. Bisa kirim ke seluruh wil Indonesia, luar pulau Jawa harap chat CS kami ya kak!', '33.jpg', 'makanan'),
(34, 'Roti Cane Coklat isi 10 Pcs / Canai / Maryam / Konde Coklat isi 10 Pcs', 18000, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: ROTI KONDE\r\n*FREE BUBBLE WRAP!*\r\n\r\nBERGARANSI 100% JIKA BARANG SAMPAI DALAM KEADAAN RUSAK DALAM JANGKA WAKTU PALING LAMBAT 3 HARI SILAHKAN KLAIM UANG KEMBALI ATAU PENGIRIMAN PRODUK YANG BARU (UNTUK JAWA BARAT).\r\n\r\nRoti maryam atau bisa juga disebut dengan Roti Cane atau Roti Canai atau Roti Konde ini dibawa masuk ke Indonesia oleh para pedagang Arab yang kemudian menjadi makanan sehari-hari di Indonesia. Dengan rasa yang sangat gurih dan juga ada yang manis, roti maryam dengan mudah menjadi makanan favorit orang Indonesia. Setelah ribuan produk terjual, kami masih setia mengeluarkan produk makanan favorit.\r\n\r\nKali ini produk kami adalah Roti Maryam / Roti Cane / Roti Konde Cokelat.\r\nMengapa kamu harus memilih produk kami?\r\n\r\n*KEUNTUNGAN MEMBELI PRODUK KAMI :\r\n\r\n1. TANPA LABEL, BISA UNTUK DI JUAL KEMBALI.\r\n2. TERDAPAT LABEL TANGGAL PRODUKSI DAN TANGGAL KADALUARSA.\r\n3. KEMASAN VACUUM YANG AMAN UNTUK MAKANAN.\r\n4. KETAHANAN DI SUHU RUANG KUAT SAMPAI 4 HARI.\r\n5. 100% TANPA BAHAN PENGAWET.\r\n6. SUDAH BANYAK DI KENAL MASYARAKAT.\r\n7. BISA DI KONSUMSI SEBAGAI PENGGANTI NASI.\r\n8. COCOK UNTUK CEMILAN DI KANTOR.\r\n9. BISA UNTUK MENU HIDANGAN DI ACARA KELUARGA.\r\n\r\n*DETAIL PRODUK :\r\n\r\n- 1 PACK ISI 10 PCS\r\n- DIAMETER ROTI CANE 10 CM\r\n- BOBOT TOTAL 500 GRAM\r\n\r\n*SARAN PENYAJIAN :\r\n\r\n- Keluarkan dari Freezer hingga mencapai suhu ruang.\r\n- Panaskan menggunakan api kecil, tambahkan mentega/butter sampai kecoklatan dan garing sebelum disantap.\r\n- Bisa di tambah dengan Meses, Keju, Susu Kental Manis.\r\n\r\n*SARAN PENYIMPANAN :\r\n\r\n- Simpan di Freezer (3 Bulan).\r\n\r\n*NOTE*\r\n\r\n- PEMESANAN DAN/ATAU PEMBAYARAN SEBELUM JAM 12.30, AKAN DI KIRIM DI HARI YANG SAMA.\r\n- BUKA SENIN - SABTU\r\n- MINGGU LIBUR\r\n\r\n\r\n** JADWAL PENGIRIMAN DI BULAN RAMADHAN AKAN DI KIRIM KE ESOKAN HARINYA SETELAH PESANAN MASUK, KARENA ADA PERUBAHAN JADWAL PRODUKSI.', '34.jpg', 'minuman'),
(35, 'Snack Ejh 50gr|Makanan Ringan Ejh - Cheese Ball', 6880, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: snack\r\nMakanan Ringan Ejh\r\n\r\nmerupakan makanan ringan yang di import dari negara malaysia dengan kemasan bag dan memiliki beberapa varian rasa yang cocok dengan selera para snackers indonesia,untuk snack ejh ini berat produknya kurang lebih (50g ) dan ber-bpom dan memiliki logo halal pada bagian kemasan depan\r\n\r\nVarian Tersedia:\r\n1.Cheese Ball\r\n2.Cheese Ring\r\n3.Chicken Ring\r\n4.Coco Crunch\r\n5.Green Pea\r\n6.Hot & Spicy\r\n7.Maco Ring/Snack Perisa Koko\r\n8.Drumstick\r\n9.Romatik\r\n\r\n\r\nTerima Kasih\r\nSalam Apiseller', '35.jpg', 'minuman'),
(36, 'Pastel Frozen isi 5pcs - Halal/ Makanan/ Enak/ Cemilan', 10000, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: frozen food\r\nTerbuat dari bahan berkualitas dengan cita rasa yang enak, dalam 1 kemasan isi 5 pcs pastel isi kentang, wortel, bihun dalam bentuk frozen siap goreng\r\n\r\nSebelum melakukan transaksi harap chat Admin kami terlebih dahulu untuk mengetahui stok yang tersedia saat ini.\r\n\r\nSETIAP PESANAN YANG MASUK AKAN DIPROSES KIRIM H+1\r\nKECUALI ADA STOK TERSEDIA KARNA ITU CHAT ADMIN TERLEBIH DAHULU YA KAK...\r\n\r\nBuyer harap paham antrian packing & jadwal pengiriman kami.', '36.jpg', 'minuman'),
(37, 'Momogi Stick Snack Makanan Ringan 12gr - Keju [1 Box @ 10 Pcs]', 10000, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Momogi Stick\r\nWAJIB PEMBELIAN KARDUS JIKA ORDER MAU DIKIRIMKAN DENGAN PACKING KARDUS.\r\n\r\nMomogi Stick Snack Makanan Kering 12gr [1 Box @ 10 Pcs]\r\n\r\nRasa: KEJU / CHEESE\r\n\r\nMomogi Stick adalah makanan ringan berbentuk stick dan berongga di bagian tengah dengan berbagai pilihan rasa. Mempunyai kemasan yang simple sehingga mudah dibawa kemana - mana. Jajanan/Snack kesukaan anak-anak dan orang dewasa dan ideal untuk dikonsumsi bersama keluarga.\r\n\r\nBPOM RI MD 273710096182\r\nSudah Halal MUI', '37.jpg', 'minuman'),
(38, 'Yummy Dimsum Siomay Ayam Non Frozen Food Dim Sum Halal Tanpa MSG', 10900, 'Kondisi: Baru\r\nWaktu Preorder: 3 Hari\r\nMin. Pemesanan: 10 Buah\r\nEtalase: Siap Makan Ready to Eat\r\nPengiriman dari Jakarta Timur. Untuk cabang lain bisa cek link tokonya pada bagian bawah deskripsi.\r\n\r\nUntuk pengiriman luar kota bisa klik link produk frozen berikut, dgn kurir Paxel :\r\nhttps://tokopedia.link/MrnEHEWsGqb\r\n\r\n1 porsi = 4 pcs\r\n(bukan 5 pcs, foto hanya ilustrasi saja)\r\nHarga tertera untuk per porsi. Tersedia harga grosir, beli banyak lebih murah.\r\n1 porsi = 4 pcs\r\nMinimum order 10 porsi.\r\nBelum melayani packing per porsi.\r\n\r\nPremium Quality Dimsum Ayam Halal dengan Varian Topping (bukan varian rasa) :\r\n+ Beef\r\n+ Jamur\r\n+ Wortel\r\n+ Udang\r\n\r\nJika ingin request topping, akan kami usahakan memberikan topping sesuai request. Tetapi mohon pengertian dan kerja sama nya jika belum sepenuh nya memberikan sesuai request, karena ketersediaan topping setiap waktu nya sangat dinamis sebab bergantung urutan order yg masuk terlebih dahulu pada dapur kami\r\n\r\nTanpa MSG Aman Dikonsumsi Anak-anak\r\nDimsum kami kirim matang, siap makan, ready to eat\r\n\r\nKetentuan Order\r\n+ Minimum order 10 porsi (40 pcs), belum melayani packing custom\r\n+ Mohon infokan tanggal dan jam acara / konsumsi dimsum, agar kami dapat menyesuaikan waktu pengiriman\r\n+ Pengiriman dilakukan via GOJEK/Grab\r\n+ Untuk kurir Same Day, order masuk setelah jam 12 siang akan dikirim esok hari\r\n+ Untuk kurir Instant, ready pengiriman jam berapapun (maks jam 4 sore, selama stok masih ada)\r\n+ Sudah termasuk saos, berupa bonus pembelian, sesuai ketersediaan stok. Jika dirasa kurang, bisa membeli saos tambahan pada link berikut : https://tokopedia.link/abfm69VsGqb\r\n+ Beli Banyak Lebih Murah. Tersedia harga grosir Rp 10.700 untuk minimum pembelian 20 porsi (80 pcs).\r\n\r\n======================\r\nCabang :\r\n\r\nCililitan JakTim = https://www.tokopedia.com/yummydimsum\r\nCempaka Putih JakPus = https://www.tokopedia.com/yummydimsumjkt2\r\nCimanggis Depok = https://www.tokopedia.com/dimsumfrozenfood\r\nBogor = (sdg renovasi, pindah lokasi)\r\nTangerang = (sdg renovasi, pindah lokasi)', '38.jpg', 'makanan'),
(39, 'PEMPEK EMAK INDAH FOOD - PEMPEK PALEMBANG ASLI - Paket Hemat 4 Pax', 186690, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Semua Etalase\r\nWAJIB TULIS VARIAN (A-F), JIKA TIDAK, MOHON MAAF DIKIRIM RANDOM SESUAI STOCK\r\n\r\n???? Emak mau berpesan dulu sebelum cucu-cucuku tersayang order yaa ????\r\n\r\nPempek Emak Indah asli Palembang merupakan resep andalan Emak sejak 1990. Terbuat dari 100% ikan tenggiri dan tepung berkualitas terbaik, tanpa pemutih, tanpa bahan pengawet, bahan kimia dan pewarna. Semua stock dikemas dengan fresh dan exp. date yang jauh. Rutin diproduksi homemade, pempek kami dikirim langsung dari Palembang dalam kemasan vacuum steril, sehingga kedap udara dan aman saat pengiriman.\r\n\r\n✔️menerima custom order acara-acara / event\r\n\r\nPempek Emak Indah memakain ikan tenggiri yang diolah dengan baik dan sepenuh hati sehingga menghasilkan rasa ikan yang STRONG, GURIH, namun TIDAK AMIS. Sehat dan aman dikonsumsi dengan keluarga dan sanak saudara karena bahan yang digunakan AMAN dan MUTU TERJAMIN\r\n\r\nMerupakan kombinasi dari paket pempek berikut (pilih 4):\r\n- Pax A (2 pcs pempek kapal selam)\r\n- Pax B (8 pcs pempek adaan/bulat)\r\n- Pax C (8 pcs pempek kulit)\r\n- Pax D (8 pcs pempek telur kecil)\r\n- Pax E (8 pcs pempek lenjer)\r\n- Pax F (8 pcs campur : 2 kulit, 2 adaan , 2 lenjer, 2 telur)\r\n\r\n*Info mimin yaa, misal: aku mau order 2 pax A, 1 pax B.... ya min :)\r\n\r\nPaket sudah termasuk : 4 cuka cair(@80ml), 3 Varian level cuka bisa Request di note :\r\n1. Cuka Pedas Mampus Lv4\r\n2. Cuka Standar Lv1\r\n3.Cuka Tidak Pedas/TP\r\n\r\nNOTE : jika tidak ada request cuka akan diberikan lv1\r\n\r\nBuat yang di luar kota estimasi sampai 2-3 hari harus pakai tambahan styrofoam+thermafrezeer :\r\nstyrofoam 20rb bisa muat order :\r\n2 pax = ini masih 1 kg (toleransi 1,3)\r\n3 pax = ini masuk 2kg\r\n\r\nStyrofoam 25rb = muat up to 4-8 pax\r\n4 pax = 2kg\r\n5-6 pax = 3kg\r\n7-8 pax = 4kg\r\n\r\nBerat : 2300 gr\r\n\r\nPackaging:\r\nPempek dikemas dan dikirim dengan kemasan vacuum dengan plastik berstandart food grade.\r\nCuka cair dikemas dengan plastik foodgrade.\r\n\r\nUmur simpan:\r\nSuhu ruang: 2 hari\r\nFreezer : 4 bulan', '39.jpg', 'minuman'),
(40, 'Original Beef Jerky (DENDENG AMERIKA) Makanan Ringan', 80000, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Snacks\r\nKini hadir dengan rasa kids friendly! tidak pedas!\r\n\r\nP-IRT 5015103030019-26\r\n\r\nBPOM RI MD 022246000500040\r\nHALAL INDONESIA ID51210001987590223\r\n\r\nKantong 50 gram = ~ 150g steak (Protein 20gram+)\r\nPeriode kedaluwarsa: 6 bulan\r\nPaling baik dikonsumsi: 3 hari setelah dibuka\r\n\r\nSemua pesanan akan diproses maksimal hingga pukul 15.00 setiap hari di hari Senin - Jumat.\r\nOrder di atas pukul 15.00 WIB akan diproses keesokan harinya.\r\n\r\nDendeng kami adalah dendeng American Style. Dipotong tipis-tipis dan penuh rasa, ini adalah camilan sehat sempurna yang penuh protein dan bahan alami. Jika Anda membeli lima paket atau lebih, pengiriman gratis.\r\n\r\nDendeng Bali Forages adalah produk handmade dalam jumlah kecil untuk memaksimalkan kesegaran produk. Dendeng kami adalah steak panggul yang didehidrasi tanpa bahan buatan, pengawet atau MSG. Semua rempah-rempah kami adalah rempah lokal dari Bali.\r\n\r\nTiap kantong berisi 50 gram daging sapi dan bisa langsung disantap (tidak perlu dimasak lagi). Paling baik dimakan dalam waktu 3 hari setelah kantong dibuka. Umur penyimpanan adalah 6 bulan saat kantong tertutup rapat. Produk tidak perlu dimasukan ke kulkas.\r\n\r\n-------------------------\r\n\r\nReady to eat\r\n50 gram bag = ~150g of steak (20grams+ Protein)\r\nExpiration period: 6 months\r\nBest consumed: 3 days after opening\r\n\r\nAll orders will be processed at 15.00 PM everyday. Orders above 15.00 PM will be processed the next day.\r\n\r\nOur beef jerky is American Style jerky. Cut thinly and full of flavor, it is the perfect healthy snack full of protein and natural ingredients..\r\n\r\nBali Forages beef jerky is handmade in small batches to maximize freshness. Our jerky is dehydrated flank steak with no artificial ingredients, preservatives or MSG. All of our spices are locally sourced from Bali.\r\n\r\nEach pack comes with 50 grams of beef and can be eaten right away. The portion is best for 1-2 people. It is best eaten within 3 days after opening the package. The shelf life is 6 months when the bag is sealed. No refrigerator is needed.\r\nLihat Lebih Sedikit', '40.jpg', 'makanan'),
(41, 'HAKAU HAKAO UDANG DIMSUM HALAL FROZEN FOOD', 2500, 'Kondisi: Baru\r\nMin. Pemesanan: 10 Buah\r\nEtalase: CEMILAN\r\nHakau Udang\r\nHarga yg tertera adalah harga per pcs Minimal order 10 pcs dan kelipatannya\r\n(10,20,30,....dst)\r\n\r\nCATATAN TOKO :\r\n1. Operasional hari biasa :\r\n-Sameday max order jam 15.00\r\ndikirim di hari yg sama.\r\n-Instan max order jam 17.00\r\ndikirim di hari yg sama.\r\nToko offline buka jam 08.00-19.00\r\n2. Operasional bulan puasa :\r\n-Sameday max order jam 14.00\r\n-Instant max order jam 15.00\r\nToko offline buka jam 08.00-17.00\r\n3. Bila URGENT / ingin cepat sampai silahkan pilih INSTANT krn driver hanya mengambil orderan kakak di toko kami dan langsung\r\nmengantarnya ke alamat kakak.\r\n4. SAMEDAY waktu tiba sekitar 5-8\r\njam setelah request driver krn driver bisa mengambil orderan dari 5-8 toko yg berbeda.\r\n5. BEBAS ONGKIR khusus untuk barang non frozen karena tiba dalam waktu 2-3 hari dan jangkauan hingga luar kota / luar pulau.\r\n6. Alangkah baiknya menanyakan stok terlebih dahulu karena produk yg di etalase juga dijual di toko offline kami.\r\n7. Apabila ada kekosongan barang\r\nakan kami kembalikan uangnya\r\natau diganti dengan barang lain\r\natas persetujuan pembeli.\r\n8. Apabila mau membeli dalam jumlah banyak tetapi barang di etalase jumlahnya sedikit, mohon chat admin supaya stoknya segera ditambahkan.\r\n9. Bagi yg mau mengirimkan paket buat saudara, teman, relasi, orang2 tercinta, kami melayani pengiriman frozen food ke area berikut :\r\nJakarta Timur, Jakarta Barat, Jakarta Pusat, Jakarta Selatan, Jakarta Utara, Bogor, Kab.Bogor, Depok, Tangerang, Kab.Tangerang, Bekasi, Kab.Bekasi, Cikarang, Cirebon, Bandung, Kab.Bandung, Kab.Bandung Barat, Cimahi, Tasikmalaya, Semarang, Yogyakarta, Sleman, Bantul, Solo, Karanganyar, Sukoharjo, Magelang, Purwokerto, Sidoarjo, Surabaya, Malang, Kab.Malang, Jember, Ngawi, Madiun, Kediri, Banyuwangi, Denpasar, Kab.Badung (Bali), Makassar, Medan. Silahkan memilih pengiriman NEXT DAY (PAXEL)\r\n10. Setelah barang diterima mohon kesediaannya untuk memberikan rating bintang 5⭐⭐⭐⭐⭐ ya kak.', '41.jpg', 'makanan'),
(42, 'Sambosa Keju Mozarella Samosa Daging Moza Per Pak / Samosa Frozen Food', 31900, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: FrozenCampuz\r\n▶ Halo, Welcome to FrozenCampuz - Delicious Food Carrying Happiness\r\n\r\nAneka Frozen Food Homemade dan Higienis\r\nCITA RASA KHAS KOTA SURABAYA\r\nAman Dikonsumsi Keluarga dan Anak - Anak\r\nHALAL, NO MSG, NO PRESERVATIVE\r\nSehat, Lezat, Gurih, Bergizi Tinggi\r\n\r\n▶ SAMOSA BEEF KEJU MOZARELLA BY FROZENCAMPUZ\r\nSamosa yang didalam isinya full daging beef dan keju mozarella. Rasa lezat dan gurih. Cita rasa khas Kota Surabaya. Isi 5 pcs/pak.Berat per pak 400 gram. Kondisi produk beku. Cara penyajiannya digoreng dengan minyak panas. Nikmat dikonsumsi dengan saus, cabai, dll.\r\n\r\n▶ NOTES\r\nProduk ini aman/tahan hingga 30 hari jika disimpan didalam freezer\r\nProduk ini rentan/cenderung cepat berubah rasa, kondisi, dll (tidak awet) di suhu ruang/chiller\r\nProses pengiriman dan penyimpanan sangat berpengaruh terhadap kualitas produk sehingga,\r\n\r\n▪️ SETELAH SAMPAI TUJUAN, mohon simpan langsung frozen kedalam FREEZER\r\n\r\n▪️ SANGAT DISARANKAN untuk pengiriman JABODETABEK => GOSEND/GRAB EXPRESS/ANTERAJA SAMEDAY ATAUPUN INSTANT\r\n\r\n▪️ SANGAT DISARANKAN untuk pengiriman LUAR JABODETABEK/KOTA/PULAU => PAXEL NEXT DAY/JNE YES\r\n\r\n▪️ Keterlambatan/Kerusakan paket saat sudah di ekspedisi di luar tanggung jawab kami/seller/toko, Dikirim oleh kami dengan kondisi baik dan fresh, Mohon pertimbangkan jasa pengiriman yang dipilih\r\n\r\n▶ KAMI MENJUAL ANEKA FROZEN BEKU\r\nAneka Risoles, Samosa, Pastel, Kroket, Kebab, Martabak, Sosis Solo, Lumpia, Dimsum, Siomay, Bakso, Pizza, Onde-Onde, Roti Maryam, Donat, Roti Bakery, dll\r\n\r\n▪️ MENERIMA PESANAN CAFE, KANTOR, RESTORAN, CATERING, KAMPUS, WISUDA, WEDDING, HAJATAN, DAN EVENT LAINNYA\r\n\r\n▪️ Untuk pemesanan frozen food dalam jumlah besar dimohon chat/call/wa pada nomor yang tercantum pada profil toko kami dan mohon kesediannya menunggu respon paling lambat 1x24 jam terutama pada masa sibuk weekdays/weekend ????\r\n\r\nTerima Kasih', '42.jpg', 'makanan'),
(43, 'Manisan Mangga Mika 5\'s PEDAS HL Ellken Healthy Food', 35000, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Traditional Snacks\r\nEllken Healthy Food\r\n\r\nManisan mangga asli :\r\n- kering alami\r\n- mengandung banyak Vitamin C dan Vitamin lainnya\r\n\r\nHL mangga kering manis (manisan mangga) terbuat dari mangga jawa pilihan dan kaya akan Vitamin C. Sangat cocok untuk ngemil kapan saja dan dimana saja.\r\nBahan : mangga, gula, asam sitrat, garam, cabai\r\n\r\nNilai Nutrisi :\r\n- Kalori : 54.1 Kal\r\n- Protein : 0.15 Gr\r\n- Lemak : 0.12 Gr\r\n- Karbohidrat : 13.93 Gr\r\n- Kadar Air : 15.28 %\r\n- Vitamin A : 25.5 Mg\r\n- Vitamin C : 19.9 Mg\r\n\r\nProduk kami telah terdaftar dan mendapat ijin dari departemen kesehatan dengan nomer P.IRT : 2143671010125-19. Sehingga kami menjamin akan kualitas dan keaslian dari produk kami. Tunggu apa lagi, klik ADD TO CART sekarang dan rasakan manfaat dari produk kami.', '43.jpg', 'makanan'),
(44, 'Dimsum Ayam Frozen Kemasan Vakum Hommade Dingdong Food isi 10', 26000, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: DIMSUM\r\nHallo Kakak, Harap Dibaca dahulu ya sebelum membeli.\r\n\r\n\r\n*Dimsum kami menggunakan bahan dasar Ayam giling fresh dan campuran bumbu lainnya\r\n*Dimsum ini Halal dan Tidak menggunakan pengawet apapun\r\n*Dimsum Ini awet hingga 4 minggu didalam bekuan atau frezer dengan suhu rata-rata (-14 s/d -18 derajat Celcius)\r\n*Berat satuan dimsum tanpa sauce : 38-39 gram\r\n*Diameter satuan dimsum : 3-4 cm', '44.jpg', 'makanan'),
(45, 'Cireng Krispy Sambal Rujak (Frozen Food)', 11500, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Makanan Frozen\r\nALABALLA FROZEN FOOD\r\n\r\nSilakan Chat Terlebih Dahulu Untuk Tanyakan Stok Ready Yaa ^^\r\n\r\n!! BELI BANYAK LEBIH MURAH!!^^\r\n\r\nCIRENG KRISPY FROZEN FOOD\r\nDengan Sambal Rujak\r\nLembut di dalam, Crispy di luar, satu kali gigit lepas di mulut, dua kali gigit jatuh cinta ...\r\n\r\nCara penyajian :\r\n1. Ambil dan tipiskan cireng\r\n2. Panaskan minyak secukupnya sampai 180 °C (api sedang) dan goreng selama 2 - 3 menit hingga garing\r\n3. Siap dihidangkan sebagai menu utama, makanan kecil, maupun hidangan pesta\r\n\r\nBerat 400gr\r\nIsi 20 Pcs\r\nSuhu ruang 2-3 hari\r\n\r\nFREE BUBBLE WRAP !!\r\n\r\ndisarankan PENGIRIMAN HANYA VIA GRAB / GOSEND / SAMEDAY / NEXT DAY !!\r\nApabila pembeli menggunakan pengiriman Reguler ke luar dari jawa barat dan basi maka seller tidak bertanggung jawab ^.^', '45.jpg', 'minuman'),
(46, 'agen distributor makanan ringan biskuit oreo soft cake pack murah', 23999, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Makanan\r\n1pack isi 12pcs @16gr', '46.jpg', 'minuman'),
(47, 'snack mikako 18gr makanan ringan rasa ayam geprek', 5500, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Semua Etalase', '47.jpg', 'minuman'),
(48, 'TASAJI FOOD ROTI MARYAM ORIGINAL (ISI 5PCS)', 14000, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: TASAJI FOOD\r\nTASAJI FOOD ROTI MARYAM ORIGINAL (ISI 5PCS)\r\n\r\n- Chat dulu untuk ketersediaan barang\r\n- Pengiriman hanya via Gojek dan Grab\r\n\r\nAl Fatih Frozen Food\r\nJam operasional Senin sd Sabtu Jam 09.00 – 17.00\r\nHari Minggu dan Libur Nasional tutup\r\n\r\nOrder Sameday terakhir jam 14.00, setelah itu akan masuk ke pesanan hari selanjutnya\r\nOrder Instant terakhir jam 16.00, setelah itu akan masuk ke pesanan hari selanjutnya', '48.jpg', 'makanan'),
(49, 'Gandum Goreng - Cemilan Sehat / Snack / Makanan Ringan', 11000, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Makaroni\r\nAgar PAKET LEBIH AMAN mohon tambahkan (add to cart) DUS ya kakak yang baik... https://tokopedia.link/NqVXdTruhxb\r\n\r\nREADY STOCK SEMUA RASA\r\nNETTO: 100 GRAM\r\n\r\n+ Terbuat ASLI dari biji Gandum semolina bukan tepung terigu\r\n+ Berserat tinggi, jadi cepat bikin kenyang cocok sekali untuk yang sedang program diet\r\n+ Digoreng menggunakan minyak nabati sekali pakai, sehingga lebih enak, renyah dan aman dikonsumsi oleh siapa saja\r\n+ Sudah terdaftar di dinkes dan berlogo halal MUI\r\n\r\nGandum Goreng tersedia dalam 8 rasa:\r\n\r\nPedas Gurih\r\nBalado\r\nBalado Jeruk\r\nKeju\r\nRumput Laut\r\nOriginal\r\nBarbeque\r\nJagung Manis\r\n\r\nBest seller : balado, barbeque, keju, pedas gurih\r\nUntuk varian non MSG : Original', '49.jpg', 'minuman'),
(50, 'DIMSUM AYAM 1000an SIOMAY FROZEN FOOD MURAH TOPPING MIX', 101000, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: frozen\r\nHARGA DI ATAS ADALAH HARGA PER PACK DIMSUM TANP\r\nA SAOS ISI 20\r\n \r\nDIJUAL PER VARIAN ISI 20 PCS\r\nVARIAN MIX = TOPPING NYA TIDAK BISA REQUEST, ISI TOPPINGNYA RANDOM\r\n\r\nKARENA DIKIRIM DALAM KEADAAN BEKU HARAP DI KUKUS KEMBALI 5 - 10 MENIT SEBELUM DI SANTAP..\r\n\r\nDikirim Keadaan Beku/Frozen dengan kemasan plastik vacum sealer\r\n\r\n100% Halal\r\n\r\nPERHATIAN !! KAMI SARANKAN HANYA UNTUK PEMBELIAN WILAYAH JAWA TIMUR SAJA. SELAIN ITU DIMOHON UNTUK TIDAK MELAKUKAN CHECK OUT JIKA TETAP MEMBELI RESIKO BASI DITANGGUNG SENDIRI. NO KOMPLAIN\r\n\r\n???????? HIMBAUAN ????????\r\nKARENA INI MAKANAN FROZEN KAMI SARANKAN KETIKA ADA EVEN PROMO DIMOHON BIJAK DALAM MEMILIH JASA PENGIRIMAN, DISARANKAN MEMAKAI JASA KIRIM INSTANT GOJEK/GRAB DAN SAMEDAY. \r\n\r\nKARENA DITAKUTKAN JASA KIRIM REGULER AKAN MENGALAMI OVERLOAD PENGIRIMAN, YANG MEMBUAT SAMPAINYA BARANG MENJADI LEBIH LAMA SEHINGGA MEMUNGKINKAN PRODUK MENJADI BASI. \r\n\r\nJIKA TETAP MEMAKAI JASA KIRIM REGULER RESIKO DITANGGUNG SENDIRI', '50.jpg', 'makanan'),
(51, 'PONCA Food Dimsum Ayam 500g isi 20', 30056, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Semua Etalase', '51.jpg', 'minuman'),
(52, 'BASRENG PEDAS DAUN JERUK 1KG SAJODO SNACK & FOOD', 50000, 'Kondisi: Baru\r\nWaktu Preorder: 7 Hari\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Semua Etalase\r\nBASRENG PEDAS DAUN JERUK 1Kg UNTUK SANTAI AKHIRNYA LAUNCHING. RASANYA PEDES NAMPOL DAUN JERUK SUPER SEGER!!!\r\n\r\nBasreng merupakan camilan khas sunda yang terbuat dari bakso ikan yang diiris tipis, lalu digoreng kering dan ditaburi bubuk cabai. Cocok dijadikan sebagai toping di berbagai makanan instan.\r\n\r\nKomposisi:\r\n\r\nTepung Tapioka, Air, Chili Flake,Chili Powder, Daun Jeruk, Minyak Sayur, Ikan Laut, Bumbu Racikan Khas Sajodo\r\n\r\n== PENGIRIMAN ==\r\n\r\n- MINGGU & HARI LIBUR NASIONAL TIDAK ADA PENGIRIMAN.\r\n\r\n- Pengiriman J&T Only\r\n\r\n- PRE ORDER / PO Pengiriman H+7\r\n\r\n- Estimasi barang sampai (1-4 hari untuk Jabodetabek dan Pulau Jawa), (3-7 hari diluar Pulau Jawa).\r\n\r\n- Pengiriman bisa lebih cepat atau lambat tergantung jasa pengiriman, pastikan jasa pengiriman yang dipilih adalah jasa pengiriman terbaik di daerah kalian.\r\n\r\n== CLAIM DAN GARANSI ==\r\n\r\nMohon untuk lampirkan bukti keadaan baik Foto atau Video Lengkap :\r\n\r\n- Saat Barang tiba\r\n\r\n- Kondisi Dus dan Segel sebelum dibuka\r\n\r\n- Video Proses Unboxing\r\n\r\n- Kondisi isi Paket Setelah Unboxing untuk Memudahkan kita dalam Proses Investigasi, karena dikhawatirkan kelalaian dari Pihak Ekspedisi yang kurang baik dalam Handle/Penanganan Paket', '52.jpg', 'makanan'),
(53, 'Kracie Popin Cookin DIY Candy Maker Japan Miniature Food', 65000, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Semua Etalase\r\nDo It Your Self Candy. Yuk buat permen sendiri.\r\nMainan anak yang kreatif dan mengedukasi dengan hasil permen yang dapat dimakan dengan rasa buah-buahan yang enak.\r\nAsli Made In Japan\r\n\r\nInsyaallah halal karena tidak mengandung gelatin hewani, melainkan menggunakan bahan pengenyal dari rumput laut (algae)', '53.jpg', 'minuman'),
(54, 'M&S FOOD - Biscuits - Plain Chocolate Digestives', 39900, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Food\r\nBest Before Date : 2 Agustus 2023\r\n\r\nUPC_Code : MSSF-747103000000\r\n\r\nHalf Coated Biscuit In Smooth Dark Chocolate\r\n\r\nB P O M Number: 235609262035\r\n\r\nProduct Weight : 300g\r\n\r\nIngredients : Wheatflour contains Gluten (with Wheatflour, Calcium Carbonate, Iron, Niacin, Thiamin) Dark Chocolate (28%) (Sugar Cocoa Mass Cocoa Butter Butter Oil (Milk) Emulsifier: Soya Lecithin Flavouring) Palm Oil Sugar Wholemeal Wheatflour (contains Gluten) Demerara Sugar Partially Inverted Sugar Syrup Raising Agent: Sodium Bicarbonate, E503, E450 Salt Barley Malt Extract (contains Gluten). Dark Chocolate contains Cocoa Solids 35% minimum.\r\n\r\nGluten Free : N\r\n\r\nSugar Free :\r\n\r\nAllergen : Wheatflour, Gluten, Milk, Soya, Barley', '54.jpg', 'minuman'),
(55, 'KASIMURA Kaki naga isi 10 pcs dragon stick frozen food naget', 18720, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Naget\r\nKaki naga\r\nTerbuat dari olahan ayam & ikan\r\nYang di balut tepung panir\r\n1 pack isi 10 pcs\r\nHarga 18.000', '55.jpg', 'minuman'),
(56, 'makanan cemilan sehat snack kripik kentang putih oven 100 gram', 35000, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: aneka keripik dan emping\r\n\r\nkeripik kentang gadung rasanya gurih dan enak, di buat dari kentang segar yang di oven membuat kripik ini lebih nikmat\r\n\r\nbisa untuk oleh oleh teman,kerabat,saudara..\r\n\r\nuntuk pembelian 500 gram ke atas\r\n\r\nhttps://tokopedia.link/CDwJhJLzClb\r\n\r\npacking mengunakan bubble warp agar dapat di terima dengan aman oleh pembeli..\r\n\r\npengiriman max jam16.00 pembelian di atas jam 16.00 akan di kirim hari berikut nya', '56.jpg', 'makanan'),
(57, 'ARSITAS Shop | Geblek Makanan Khas Kulon Progo | Mentah dan Komplit', 15000, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Semua Etalase\r\nGeblek merupakan makanan khas dari Kabupaten Kulon Progo Daerah Istimewa Yogyakarta. Dibuat dari Pati Singkong dan diolah secara tradisional, tanpa MSG sehingga makanan ini dijamin sehat.\r\n\r\nRasanya Enak dan Gurih. Teksturnya empuk. Apalagi sudah ada sambal/sausnya yang semakin menambah nikmatnya Geblek itu sendiri. Sangat cocok dan pas jika disandingkan dengan The maupun Kopi.\r\n\r\nGeblek juga bisa dijadikan buah tangan atau buat kirim-kirim ke tetangga dan saudara.', '57.jpg', 'minuman'),
(58, 'ALAMII FOOD - Puff HEALTHY Snack Anak CEMILAN BISKUIT MPASI BAYI 30Grm', 19000, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Cemilan Sehat\r\nCEMILAN PUFF PREMIUM / MAKANAN BAYI PREMIUM QUALITY!\r\nTersedia dalam 7 variants rasa:\r\n- Strawberry Yogurt\r\n- Cheese\r\n- Golden Veggie\r\n- Peanut Butter\r\n- Cheese Tomato\r\n- Chocolate\r\n- Chicken Mushroom (NEW!)\r\n\r\nAlamii Puffs - Snack Bayi/Anak Sehat dan Lezat baru dari Alamii Food! Terbuat dari beras dan jagung pilihan, bahan baku premium dan natural sehingga menghasilkan puffs yang bertekstur lembut di mulut. Cocok untuk dikonsumsi dari umur 8 bulan\r\n\r\nKenapa Alamii Puffs?\r\n● Premium Natural Ingredients\r\n● Menggunakan Sunflower Oil yang rendah lemak jenuh\r\n● Baked. NEVER Fried / Tidak Digoreng\r\n● No MSG / Tanpa Penguat Rasa\r\n● No Preservatives / Tanpa Pengawet\r\n● No Artificial Flavors & Color / Tanpa Perasa & Pewarna Sintetis\r\n● Tekstur puffs yang lembut dan mudah lumer di mulut\r\n\r\nNikmati Alamii Puffs dalam 4 varian:\r\nStrawberry Yogurt Puffs\r\n● Slightly sweet and tangy flavor. So fruity, light and airy!\r\n● Dibuat dengan premium Strawberry dan Yogurt powder dari Australia\r\n.\r\nCheese Puffs\r\n● Keju Cheddar Asli dari Australia\r\n● Sumber Calcium, Lemak sehat, Protein, dan Vitamins\r\n.\r\nGolden Veggie Puffs\r\n● Rasa Jagung Manis Premium dan Wortel\r\n● Carrot Powder (Bubuk Wortel) dibuat dari 100% Wortel\r\n● Sumber beta-carotene, Vitamin A, and antioxidant\r\n.\r\nPeanut Butter Puffs\r\n● Rich & Smooth Peanut Butter\r\n● Kaya dengan Protein', '58.jpg', 'makanan'),
(59, 'Bentonite Clay Food Grade 10 gram 10gram Clarification Clarifier Agent', 27000, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Kesehatan\r\n*** harga tertera untuk per bungkus (10g) ***\r\n\r\nLarutkan dengan air sebelum menggunakan produk 3 jam. siap digunakan!\r\n10g = 10-20 kg juice\r\nJangan mengaduk kuat-kuat saat menyiapkan larutan untuk menghindari banyak busa.\r\n\r\nUntuk lebih jelas, silahkan lihat gambar\r\nSemoga bermanfaat\r\nTerimakasih', '59.jpg', 'makanan');
INSERT INTO `produk` (`id`, `nama`, `harga`, `deskripsi`, `file`, `kategori`) VALUES
(60, 'beng beng 1 dus 17 pcs 25 gr / wafer / makanan ringan', 32775, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Snack Wafer dan Cemilan\r\nMerupakan wafer persembahan Beng Beng dengan coklat pilihan yang nikmat untuk Anda. Wafer ini terbuat dari bahan pilihan yang nikmat. Selain itu, wafer ini memiliki kemasan yang praktis dan mudah untuk dikonsumsi. Ideal dijadikan cemilan sehat saat santai Anda bersama keluarga.\r\n\r\n- Isi 17 Pcs\r\n- Pengambilan 1 dus bisa order x 8 (1 dus isi 8 pack) harga lebih hemat\r\n\r\n** Kenapa Harus Belanja di Toko Kami\r\n\r\n- Produk kami jual dijamin aman dan masa expired masih panjang (Jika Anda menemukan Produk Expired atau Masa Expired Mepet akan kami ganti uang anda 2x lipat dari total belanja)\r\n- Pengiriman Cepat dan Aman\r\n- Packingan Aman dan Rapih Karena Kami Pack Dengan Dus + Bablewrap (Tanpa Dikenakan Biaya Tambahan)\r\n- Banyak Voucher dan Promo Lainnya\r\n- Admin Fast Response\r\n\r\nHappy Shopping', '60.jpg', 'makanan'),
(61, 'Java Super Food, Sushi Nori Gold Rumput Laut', 31900, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Kebutuhan Memasak\r\nINFORMASI PRODUK:\r\nSushi Nori dari Java Super Food Merupakan Sushi Nori Praktis Yang Digunakan Untuk Menggulung Sushi atau Kimbab. Sushi atau susyi adalah makanan Jepang yang terdiri dari nasi yang dibentuk bersama lauk berupa makanan laut, daging, sayuran mentah atau sudah dimasak. Rumput Laut ini 100% Original, Teksturnya Segar Dan Renyah, Tidak ada bahan pengawet\r\n- Berat: 15-125gr\r\n- Isi: 5-50 lembar\r\n- Penyimpanan: Suhu Ruangan (kering)\r\n- Sertifikasi : Halal Terverifikasi MUI.\r\n\r\nINFORMASI PENGIRIMAN:\r\n- Pengiriman ke alamat kantor & butuh cepat sampai sangat dianjurkan [WAJIB] menggunakan pengiriman kurir INSTANT.\r\n- FYI bahwa kami sebagai penjual di berikan batas waktu oleh Tokopedia 1x24 jam (Minimum) untuk melakukan pengiriman ke pembeli.\r\n- Kami memproses pesanan segera SETELAH JAM BUKA TOKO, sesuai antrian pesanan.\r\n\r\nKETENTUAN BATAS PENGIRIMAN:\r\n1. Pesanan menggunakan Kurir SameDay sebelum jam 14:00 diproses di hari yang sama.\r\n2. Pesanan menggunakan Kurir INSTANT sebelum jam 16:00 diproses di hari yang sama.\r\n*DILUAR KETENTUAN TERSEBUT AKAN DIPROSES DI HARI BERIKUTNYA.\r\n\r\nSYARAT PENGAJUAN KOMPLAIN:\r\nKami hanya menerima komplain yang disertai dengan video unboxing. (Video dari awal paket sebelum dibuka hingga selesai).\r\n*KOMPLAIN TANPA VIDEO UNBOXING TIDAK DAPAT DIPROSES.\r\n\r\nMEMBELI = MENYETUJUI KETENTUAN YANG DITETAPKAN.', '61.jpg', 'minuman'),
(62, 'S Ayam Udang Super Special FamilyPack-Frozen Food Halal-Dimsum Mbledos', 49500, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Super Special Family Pack 500gr\r\nFamily Pack :\r\n\r\nSiomay Ayam Udang Super Special Isi 500 Gram - Frozen Food Halal Mbledos Family Pack\r\nSpesialis dimsum murah tapi enak\r\n\r\nFrozen food\r\n1 pack isi 12 - 20 pcs\r\nOriginil Home made\r\nFree ongkir - bisa COD\r\nHalal MUI - BPOM proses\r\nPerusahaan berpengalaman 10 th\r\n\r\nDimsum PERTAMA yg pakai bahan\r\nAyam muda (lbh empuk dan lezat)\r\n\r\nBENEFIT BELANJA DI TOKO KAMi :\r\n⁃ Produsen (tangan pertama)\r\n⁃ Pastinya lbh murah\r\n⁃ Dijamin stock selalu baru\r\n⁃ Terlengkap varian nya\r\n⁃ Service & kirim fast respon\r\n⁃ Banyak promo & bonus\r\n⁃ Minggu & tgl merah ttp kirim\r\n*Bandingin aja dgn toko lain\r\n\r\nKELEBIHAN DIMSUM MBLEDOS :\r\n⁃ Murah\r\n⁃ Rasa enak\r\n⁃ Dapat banyak\r\n⁃ Besar\r\n⁃ Bahan berkualitas\r\n⁃ Bersih & higienis\r\n⁃ Pakaging bagus, kuat & save\r\n*Ini jelas bukan dimsum pasaran\r\n\r\nBAIK UNTUK :\r\n⁃ Anak-anak\r\n⁃ Remaja\r\n⁃ Dewasa\r\n⁃ Orang tua\r\n\r\nDISARANKAN UNTUK :\r\n⁃ Cemilan nonton tv\r\n⁃ Main game\r\n⁃ Kumpul keluarga\r\n⁃ Kumpul teman, dll.\r\n(Pokok nya segala suasana\r\nbikin lbh seru deh kak)\r\n\r\nPROMO & BONUS :\r\n1. Disc 20 %\r\n2. Beli lbh 5 pack dpt pot hrg\r\n4. Bonus supit/chopstick\r\n5. Bonus resep kekinian\r\n*WoW.. bnyk bgt promo & bonus nya\r\nYuk kak segera check out in\r\nJgn smp Kehabisan, krn terbatas !\r\n\r\nKOMPOSISI :\r\nAyam, terigu, sayuran, rempah, garam, bawang putih, minyak wijen\r\n(Semua bhn alami, bersih & sehat)\r\n\r\n~ DIMSUM DI PROSES\r\nMengikuti standar BPOM & MUI\r\njadi garansi aman di konsumsi\r\n~ DIMSUM DI KEMAS\r\nSudah matang & beku ya kak\r\n~ DIMSUM SEBELUM DI KIRIM\r\nTelah melewati standar kuality kontrol & seleksi yg ketat\r\n\r\nSARAN PENYIMPANAN :\r\n> Freezer (Beku) - 18’ = 2 bln\r\n> chiller/kulkas - 4’ = 7 hr\r\n> Suhu ruangan = 2 hr\r\n\r\nSARAN MEMASAK :\r\n> Kukus / Goreng / Grill = 5 - 10 mnt\r\n\r\nMELAYANI DIJUAL LAGI :\r\n⁃ Open Reseller / agen\r\n⁃ Open Dropshiper\r\n*Hrg grosir, beli lbh 5 pack dpt pot\r\nMau lbh murah ? Kakak bisa\r\njd member, pot hrg up to 15%\r\nHub. Cs kami ya kak\r\n\r\nHappy shopping & terima kasih telah belanja di toko kami.', '62.jpg', 'makanan'),
(63, 'HEALTHY FOOD MIX 100% ORIGINAL | FAMILY NUT PREMIUM', 50000, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: TRAIL MIX\r\n\"FAMILY NUT\"\r\nHEALTHY MIXED NUT 100% ORIGINAL | HEALTHY FOOD MIX PREMIUM\r\n\r\n\r\nKomposisi :\r\n- Original Pistachio\r\n- Original Hazelnut\r\n- Original Macadamia\r\n- Original Pumpkin Seed\r\n- Original Sunflower Seed\r\n- Original Cashew Roasted\r\n- Original Almond Roasted\r\n- Original Walnut Roasted\r\n\r\n\r\n--- SIAP MAKAN ---\r\nFresh karena setiap hari kami produksi\r\n\"Dijamin ketagihan\"\r\n\r\n\r\n\"HEALTHY FOOD - HEALTHY INGREDIENTS - HEALTHY LIFE - HAPPY LIFE\"', '63.jpg', 'minuman'),
(64, 'Pastel Daging Mini 8 pcs Rayafood Frozen Food', 41800, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Semua Etalase\r\nPastel Daging (Mini) legendaris dari Rayafood merupakan camilan best seller yang wajib ada di rumah. Terbuat dari perpaduan rempah tradisional nusantara dan tanpa bahan pengawet sehingga aman dikonsumsi. Kulit pastel yang gurih dan renyah serta isi daging berlimpah sangat cocok disajikan saat acara keluarga. Dilengkapi dengan sambel kacang nikmat yang membuat Anda sekali mencoba tidak bisa berhenti.\r\n\r\nDetail Produk\r\nJenis Produk: Frozen Food\r\nProduk: Pastel Daging\r\nBahan: Tepung, Daging, Rempah Pilihan, dan Tanpa Bahan Pengawet\r\nKemasan: Box\r\nIsi: 8 pieces\r\n\r\nCara Penyajian\r\n• Siapkan wajan dan panaskan minyak\r\n• Keluarkan produk dari kemasan dan goreng dengan api sedang 5-8 menit hingga kuning keemasan\r\n• Keluarkan sambel kacang Rayafood tambahkan dengan air hangat sesuai selera\r\n• Siap untuk disajikan\r\n\r\nIsi Paket\r\n• 1 box Pastel Daging (Mini)\r\nExtra Sambel Kacang\r\n\r\nPERHATIAN\r\nSimpan di Tempat Beku -18°C', '64.jpg', 'minuman'),
(65, 'KERIPIK BAYAM 200GR - KRIPIK BAYEM KREMES MAKANAN RINGAN CEMILAN', 11500, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Semua Etalase\r\n\r\nBagi pembeli, sangat disarankan untuk segera memindahkan ke wadah yang kedap udara (tupperware atau toples) agar kualitas kerenyahan dan kegurihan tetap terjaga.\r\n\r\nNote : kami mohon kerjasamanya agar segera melakukan konfirmasi saat produk sudah diterima. Terima kasih.\r\n\r\n#snack #snackmurah #camilan #cemilan\r\n#snackkekinian #snackrenyah #snackgurih #agensnack #snackkeju\r\n#keju #coklat #emping #kerupuk #krupuk #kacang #pisang #kupinggajah #mie\r\n#mielidi #makaroni #macaroni #sumpia #tempekeripik #keripiksingkong\r\n#kue #soes #kacangmede #kacangjaipong #kacangkoro #astor #cendolkeju #discount #promo\r\n#kerupukikan #empingmanis #talas #tales #ubi #keripikpangsit\r\n#marneng #marning #kupinggajah #pilus #sukro #biskuit #keripiksingkong\r\n#stikkentang #kacangkoro #koro #kripikpisang #keripikpisang\r\n#kerupukkulit #kacangkedelai #donat #momogi #rengginang #stikkentang #kacangjaipong #sumpia\r\n#pilussukro #kacangjaipong #pangsit #untiruntir #stikbawang #kacangoven #keripiktahu\r\n#pisangsale #pisangmanis #pastelabon #kacangkapri #dodolgarut #kacangovenrenyah', '65.jpg', 'makanan'),
(66, 'Dimsum Siomay Ayam Frozen Food Dim Sum Halal Tanpa MSG by Yummy Dimsum', 54500, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Semua Etalase\r\nDimsum Premium Quality By Yummy Dimsum\r\nSpesialis Dimsum yang Yummy\r\n\r\n1 pack isi = 20 pcs\r\n\r\nDikirim dalam keadaan FROZEN/BEKU.\r\nTahan 1 bulan disimpan dalam freezer, sejak pembelian. Cukup dikukus terlebih dahulu sebelum disajikan.\r\nMix topping (belum bisa request topping)\r\n\r\nDimsum Ayam Halal dengan Mix Random Varian Topping (bukan varian rasa) :\r\n+ Ayam\r\n+ Beef\r\n+ Jamur\r\n+ Wortel\r\n+ Udang\r\n\r\nTanpa MSG Aman Dikonsumsi Anak-anak\r\n\r\nKetentuan Order\r\n>> Pengiriman dilakukan via GOJEK/Grab\r\n>> Bisa kirim di hari yg sama jika masih ada slot pengiriman\r\n>> Pengiriman JNE YES kami non aktifkan karena sedang kami evaluasi. Untuk luar kota kami sarankan gunakan kurir Paxel. (Maksimum 6 pack per paket Paxel)\r\n>> Termasuk saos sbg bonus pembelian. Tersedia juga saos tambahan bisa diorder pada link berikut : https://www.tokopedia.com/yummydimsumjkt2/saos-kuah-bumbu-dimsum-by-yummy-dimsum\r\n>> Beli Banyak Lebih Murah. Tersedia harga grosir Rp 53.500 untuk minimum pembelian 4 pack.', '66.jpg', 'makanan'),
(67, 'keripik pisang kepok bangka rasa manis- snack bangka - makanan bangka', 32000, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Semua Etalase\r\nsesuai di kemasan produk\r\n\r\nberat +/- 300gr\r\n\r\nberat di invoice kami sesuaikan untuk pengiriman ya\r\n\r\nthx u', '67.jpg', 'minuman'),
(68, 'agen distributor makanan ringan snack oops baked chicken tomato 45gr', 4499, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Makanan\r\n45gr\r\n\r\n*smua produk ready dan siap krm\r\n*cocok banget tuk kaka2 yg WFH, stock drmh, online school, sumbangan (berbagi), bazzar, acara ultah (goodie bag maupun snack tower), acara kantor,dll\r\n*pengiriman cepat (pesan sblm jam 5 sore masuk pengiriman hari yang sama, diatas itu masuk bsknya)kecuali hari sabtu/minggu terkadang kurir tidak pick up. mohon sabar menunggu ya\r\n*packing aman\r\n*disarankan memilih jasa penambahan dus supaya packing super aman sampai tujuan terlebih utk pembelian diluar kota\r\n*melayani pembelian ecer,grosir maupun partai\r\n*exp lama karena smua produk baru dan masuk terus\r\n*komplain harus disertai video unboxing karena sblm krm pasti kita cek terlebih dahulu\r\n*happy shopping^^', '68.jpg', 'makanan'),
(69, 'Makanan Bakpao Karakter Lucu Karapao', 32000, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Makanan\r\nPremium KARAPAO. Cemilan sehat dan menyenangkan untuk keluarga di rumah.\r\n\r\nDi dalam 1 paket terdapat 6 varian rasa.\r\nReady Paket :\r\n\r\n1. Tsum A (Choco Tiramisu, Bold Chocolate, Chocomaltine, Taro, Kacang Merah, Coklat Pisang)\r\n\r\n2. Tsum B (Coklat, Keju, Cappuccino, Kacang Hijau, Coklat Keju, Blueberry)\r\n\r\n3. Karapao 6A (Strawberry, Coklat, Keju, Vanila, Durian, Coklat Kacang)\r\n\r\n4. Karapao 6B (Vanilla, Coklat, Keju, Strawberry, Tiramisu, Kacang Merah)\r\n\r\n5. New Moody (Strawberry Cheese, Cappucino, Choco Taro, Choco Cheese Cheddar, Chocomatcha, Choco Orange)\r\n\r\nDiameter Karapao 7,5-8 cm dengan berat ±50 gram setiap pcs-nya.\r\n\r\nKARAPAO dibuat menggunakan bahan baku terbaik di kelasnya. Komposisi bahan bakunya terdiri dari terigu, gula, garam, baking powder, ragi, air, mentega putih, dan pewarna makanan. KARAPAO TIDAK menggunakan bahan baku telur dan susu.\r\n\r\nUntuk penyimpanan, KARAPAO tahan :\r\n± 36 jam di suhu ruang\r\n± 6 hari di dalam lemari pendingin atau chiller\r\n± 5 bulan di dalam freezer (penyimpanan beku)\r\n\r\nDisarankan disimpan dalam keadaan beku jika tidak dikonsumsi.\r\n\r\nProduk dikirim dalam keadaan beku. Kukus selama kurang lebih 5 menit dengan air mendidih. Sajikan dan nikmati selagi hangat.\r\n\r\nTidak hanya lucu & lezat, makanan ini bisa bikin keluarga jadi lebih happy, terutama anak-anak.', '69.jpg', 'minuman'),
(70, 'DONALD CHEWY JELLYGUM 24gr YOGURT MAKANAN RINGAN CEMILAN ANAK JELLY', 460, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: CEMILAN SNACK MINUMAN\r\nDONALD CHEWY JELLYGUM 24gr YOGURT BUBBLEGUM COLA LYCHEE LECI GRAPE STRAWBERRY MAKANAN RINGAN CEMILAN ANAK JELLY GUM YOGHURT PUDING JELI GROSIR MURAH\r\n\r\nKEMASAN : 24 GRAM\r\nHARGA TERTERA ADALAH PER PCS\r\nVarian Rasa :\r\nYOGURT\r\nCOLA\r\nBUBBLEGUM\r\nGRAPE\r\nSTRAWBERRY\r\nLECI\r\n\r\nWAJIB BACA SEBELUM MEMBELI :\r\n\r\n* HARAP MEMBELI BUBBLE WRAP / KARDUS UNTUK KEAMANAN PADA SAAT PENGIRIMAN\r\n* BARANG RUSAK / PECAH DILUAR TANGGUNG JAWAB KAMI BILA TIDAK MEMBELI BUBBLE WRAP\r\n* Semua barang yang kami kirim sudah di cek terlebih dahulu untuk kelengkapan dan kondisi nya.\r\n* Jika ada kerusakan yang timbul saat pengiriman barang maka hal tersebut di luar tanggung jawab kami, karena barang yang kami kirim sudah di cek kualitasnya.\r\n* UNTUK PRODUK SNACK / MAKANAN RINGAN , JIKA LUMER ( MENCAIR ) karena kepanasan dalam pengiriman, MENJADI TANGGUNG JAWAB PEMBELI silahkan dipikirkan produk yang di beli dan jarak ke konsumen.\r\n* Jika stock kosong, di kirim random warna / motifnya (Berikan keterangan cancel jika tidak mau random).\r\n* Kami tidak akan mengirimkan barang yang pecah, rusak & bekas.\r\n* Barang tidak BERGARANSI / NO RETUR.\r\n* Kami TIDAK menerima komplain/penukaran yang disebabkan pembeli tidak membaca catatan toko.\r\n* DIWAJIBKAN agar pembeli dapat merekam video saat pembukaan paket. Tanpa adanya bukti video, akan sangat sulit bagi kami untuk memproses keluhan Anda.\r\n\r\nMEMBELI BERARTI TELAH SETUJU DENGAN PERJANJIAN DIATAS. KALAU KEBERATAN SILAHKAN CEK TOKO SEBELAH. TERIMA KASIH !!\r\n\r\n#snack #makananringan #wafer #wafello #chocoblast #buttercaramel #mayora #roma\r\n#cemilan #cemilananak #bengbeng #reguler', '70.jpg', 'minuman'),
(71, 'KACANG ALMOND PANGGANG UTUH ALARIC FOOD 40gr', 11250, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Snack Sehat\r\nInfo jadwal pengiriman:\r\nPengiriman senin-sabtu (Minggu tidak ada pengiriman) mulai pk 11.00 WIB, orderan yang masuk diatas pk 16.00 WIB akan masuk pengiriman besok pagi nya\r\nPengemasan paket menggunakan kardus/bubble akan disesuaikan dengan jumlah pesanan\r\n\r\nREADY STOCK\r\nSelama barang masih ada di etalase berarti stock masih ada dan bisa dipesan\r\n\r\nKETERANGAN DAN SPESIFIKASI PRODUK:\r\nKacang Almond pilihan yang dipanggang, kacang almond dengan berbagai manfaat antara lain:\r\n1. Menjaga kesehatan jantung, tulang, kulit, dan mata\r\n2. Mengontrol gula darah\r\n3. Menurunkan risiko kenker\r\n4. Menjaga berat badan, meningkatkan produksi energi, mengurangi inlamasi dan masih banyak lagi\r\nKacang almond sangat cocok untuk dijadikan cemilan sehat, dan ada banyak cara untuk menikmati almond\r\n\r\nTersedia dalam 3 varian:\r\n1. Original Roasted\r\n100% Almond\r\n2. Sweet chocolate Roasted\r\nKomposisi: Almond panggang, gula, minyak biji bunga matahari, ekstrak coklat\r\n3. Hot Spicy Lime Leaves roasted\r\nKomposisi:\r\nSertifikasi: Almond panggang, gula, minyak biji bunga matahari, daun jeruk, cabai, penyedap\r\n\r\nHalal MUI: 01101089730713\r\n\r\nUkuran:\r\nBerat Netto 40gr\r\n\r\nPaket 1kg: Muat 15Pack', '71.jpg', 'minuman'),
(72, 'M&S FOOD - Permen - Percy Piglets Percy Pig Gummy, 170 g', 55900, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Food\r\nUPC : MSSF-390194000000\r\nBest Before Date: 11 Juli 2023\r\n\r\nProduct Description : soft fruit flavour gums made with fruit juice\r\n\r\nBPOM Number : 224509410035\r\n\r\nProduct Weight : 170 g\r\n\r\nIngredients : Glucose Syrup Sugar Modified Potato Starch Dextrose Modified Tapioca Starch Fruit Juice from Concentrates (3.5%) (Apple, Mandarin, Elderberry) Acid: Citric Acid, Malic Acid, Lactic Acid Potato Protein Flavourings Fruit Concentrates (Red Grape, Elderberry) Gelling Agent: Pectin Glazing Agent: Beeswax Caramelised Sugar Syrup\r\n\r\nAllergens: Not suitable for Milk allergy sufferers', '72.jpg', 'makanan'),
(73, 'Kacang Garing Sihobuk / Makanan Ringan Khas Tapanuli Utara 200 Gram', 20900, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Produk terjual\r\nKacang Garing Sihobuk 140- 170 Gram\r\n\r\nKacang Garing Sihobuk adalah makanan ringan/camilan santuy/teman nongkrong/jajanan khas Sumatera Utara yang berasal dari Desa Sihobuk, Tarutung, Tapanuli Utara.\r\n\r\nNama Sihobuk adalah nama merk dagang yang diambil dari nama desa Sihobuk, tidak terlalu berbeda dengan kacang lain, namun kacang tersebut telah disortir dan dipilih yang terbaik untuk dijual. Kacang garing sihobuk telah menjadi oleh-oleh terkenal, bahkan sampai ke luar negeri.\r\n\r\nKacang garing sihobuk tersebut dimasak di kuali besar yang telah diisi dengan pasir, diaduk atau digongseng supaya kacang masak, dan garing secara merata.\r\n\r\nCocok Untuk Camilan Dan Oleh-oleh Khas Daerah Dingin Tapanuli Utara\r\n\r\n#kacangkulit #kacanggaring #oleholeh #jajanan #snack #makanankering #khasmedan #khassumut', '73.jpg', 'makanan'),
(74, 'Come Food Red Bean 2,1kg / Comefood kacang merah Taiwan Topping', 125000, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: comefood\r\nMerk : Comefood\r\n\r\nNetto : 2,1 kg\r\n\r\nRed bean ini bisa untuk topping dessert kekinian ????\r\nAsli Taiwan\r\n\r\nAman kirim luar kota', '74.jpg', 'minuman'),
(75, 'Dimsum Ayam Frozen Kemasan Vakum Hommade Dingdong Food isi 10', 26000, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: DIMSUM\r\nHallo Kakak, Harap Dibaca dahulu ya sebelum membeli.\r\n\r\n\r\n*Dimsum kami menggunakan bahan dasar Ayam giling fresh dan campuran bumbu lainnya\r\n*Dimsum ini Halal dan Tidak menggunakan pengawet apapun\r\n*Dimsum Ini awet hingga 4 minggu didalam bekuan atau frezer dengan suhu rata-rata (-14 s/d -18 derajat Celcius)\r\n*Berat satuan dimsum tanpa sauce : 38-39 gram\r\n*Diameter satuan dimsum : 3-4 cm', '75.jpg', 'minuman'),
(76, '(Best Seller) Siomay Ayam - Siomai Chicken FROZEN FOOD DIMSUM SPESIAL', 29500, 'Kondisi: Baru<br />\nMin. Pemesanan: 1 Buah<br />\nEtalase: SUPER SPECIAL PRAKTIS PACK<br />\nSuper Spesial Praktis Pack :<br />\n<br />\n(Best Seller) Siomay Ayam - Siomai Chicken FROZEN FOOD DIMSUM SPESIAL<br />\nSpesialis dimsum murah tapi enak<br />\n<br />\nFrozen food<br />\nIsi 10 Pcs<br />\nOriginil Home made<br />\nFree ongkir - bisa COD<br />\nHalal MUI - BPOM proses<br />\nPerush berpengalaman 10 th<br />\n<br />\nDimsum PERTAMA yg pakai bahan<br />\nAyam muda (lbh empuk dan lezat)<br />\n<br />\nBENEFIT BELANJA DI TOKO KAMi :<br />\n⁃ Produsen (tangan pertama)<br />\n⁃ Pastinya lbh murah<br />\n⁃ Dijamin stock selalu baru<br />\n⁃ Terlengkap varian nya<br />\n⁃ Service &amp; kirim fast respon<br />\n⁃ Banyak promo &amp; bonus<br />\n⁃ Minggu &amp; tgl merah ttp kirim<br />\n*Bandingin aja dgn toko lain<br />\n<br />\nKELEBIHAN DIMSUM MBLEDOS :<br />\n⁃ Murah<br />\n⁃ Rasa enak<br />\n⁃ Dapat banyak<br />\n⁃ Besar<br />\n⁃ Bahan berkualitas<br />\n⁃ Bersih &amp; higienis<br />\n⁃ Pakaging bagus, kuat &amp; save<br />\n*Ini jelas bukan dimsum pasaran<br />\n<br />\nBAIK UNTUK :<br />\n⁃ Anak-anak<br />\n⁃ Remaja<br />\n⁃ Dewasa<br />\n⁃ Orang tua<br />\n<br />\nDISARANKAN UNTUK :<br />\n⁃ Cemilan nonton tv<br />\n⁃ Main game<br />\n⁃ Kumpul keluarga<br />\n⁃ Kumpul teman, dll.<br />\n(Pokok nya segala suasana<br />\nbikin lbh seru deh kak)<br />\n<br />\nPROMO &amp; BONUS :<br />\n1. Disc 20%<br />\n2. Beli lbh 5 pack dpt pot hrg<br />\n4. Bonus supit/chopstick<br />\n5. Bonus resep kekinian<br />\n*WoW.. bnyk bgt promo &amp; bonus nya<br />\nYuk kak segera check out in<br />\nJgn smp Kehabisan, krn terbatas !<br />\n<br />\nKOMPOSISI :<br />\nAyam, terigu, sayuran, rempah, garam, bawang putih, minyak wijen<br />\n(Semua bhn alami, bersih &amp; sehat)<br />\n<br />\n~ DIMSUM DI PROSES<br />\nMengikuti standar BPOM &amp; MUI<br />\njadi garansi aman di konsumsi<br />\n~ DIMSUM DI KEMAS<br />\nSudah matang &amp; beku ya kak<br />\n~ DIMSUM SEBELUM DI KIRIM<br />\nTelah melewati standar kuality kontrol &amp; seleksi yg ketat<br />\n<br />\nSARAN PENYIMPANAN :<br />\n&gt; Freezer (Beku) - 18&rsquo; = 2 bln<br />\n&gt; chiller/kulkas - 4&rsquo; = 7 hr<br />\n&gt; Suhu ruangan = 2 hr<br />\n<br />\nSARAN MEMASAK :<br />\n&gt; Kukus / Goreng / Grill = 5 - 10 mnt<br />\n<br />\nORDER &amp; PENGIRIMAN :<br />\na. Instan<br />\n⁃ Order sebelum jam 15.00 WIB, dikirim di hari yg sama<br />\n⁃ Pakai gosend estimasi sampai 1 hingga 2 jam<br />\nb. Regular (free ongkir)<br />\n⁃ Order sebelum jam 14.30 WIB, dikirim di hari yg sama<br />\n⁃ Ekspedisi yg di pakai : J&amp;T dan paxel<br />\nc. Bisa kirim ke seluruh wil Indonesia, luar pulau Jawa harap chat CS kami ya kak!', '76.jpg', 'makanan'),
(77, 'Shrimp Spring Roll / Lumpia Udang', 62000, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: Semua Etalase\r\nShrimp Spring Roll / Lumpia Udang\r\n\r\nLumpia udang.\r\nIsi 30 pcs @16g\r\n\r\n100% HALAL\r\nReady Stock\r\nSemua produk yang terjual dalam kondisi beku / Frozen.\r\n\r\nKelebihan membeli di Toko Tani Karawaci:\r\n1. 100% HALAL\r\n2. Kami adalah Supplier tangan pertama yang menjadikan Harga dan Kualitas kami TERBAIK\r\n3. Semua foto produk kami ASLI\r\n4. Kualitas barang terjamin baik\r\n5. Mengutamakan kebersihan\r\n6. Memprioritaskan kepuasan pelanggan.\r\n\r\nS & K CANCEL/PENGEMBALIAN BARANG\r\n- Kami hanya menerima komplain barang tidak sesuai apabila ada video unboxing barang\r\npertama kali saat barang sampai (dalam keadaan video kardus / kantong plastik belum dibuka).\r\nSilahkan kirim ke 087767646482\r\n- Barang tidak sampai rusak, dan kemasan tidak terbuka\r\n- Tidak menerima yang sudah dicairkan, diolah, dipotong-potong dll\r\n- Barang jangan sampai hilang\r\n- Kesalahan penulisan alamat/pengaturan titik dari customer bukan menjadi\r\ntanggung jawab kami\r\n- Membeli = Setuju\r\n\r\nPengiriman dilakukan menggunakan Gojek & Grab, Same Day & Instant Courier. Kami merekomendasikan mengunakan jasa INSTANT COURIER untuk menjaga kualitas barang agar tetap fresh.\r\n\r\nTerimakasih.', '77.jpg', 'minuman'),
(78, 'Kuotie - Wotiek Gyoza Kuotiek Wotie Jiaozi FROZEN FOOD DIMSUM SPESIAL', 37500, 'Kondisi: Baru\r\nMin. Pemesanan: 1 Buah\r\nEtalase: SUPER SPECIAL PRAKTIS PACK\r\nSuper Spesial Praktis Pack :\r\n\r\nKuotie - Wotiek Gyoza Kuotiek Wotie Jiaozi FROZEN FOOD DIMSUM SPESIAL\r\nSpesialis dimsum murah tapi enak\r\n\r\nFrozen food\r\nIsi 10 Pcs\r\nOriginil Home made\r\nFree ongkir - bisa COD\r\nHalal MUI - BPOM proses\r\nPerush berpengalaman 10 th\r\n\r\nDimsum PERTAMA yg pakai bahan\r\nAyam muda (lbh empuk dan lezat)\r\n\r\nBENEFIT BELANJA DI TOKO KAMi :\r\n⁃ Produsen (tangan pertama)\r\n⁃ Pastinya lbh murah\r\n⁃ Dijamin stock selalu baru\r\n⁃ Terlengkap varian nya\r\n⁃ Service & kirim fast respon\r\n⁃ Banyak promo & bonus\r\n⁃ Minggu & tgl merah ttp kirim\r\n*Bandingin aja dgn toko lain\r\n\r\nKELEBIHAN DIMSUM MBLEDOS :\r\n⁃ Murah\r\n⁃ Rasa enak\r\n⁃ Dapat banyak\r\n⁃ Besar\r\n⁃ Bahan berkualitas\r\n⁃ Bersih & higienis\r\n⁃ Pakaging bagus, kuat & save\r\n*Ini jelas bukan dimsum pasaran\r\n\r\nBAIK UNTUK :\r\n⁃ Anak-anak\r\n⁃ Remaja\r\n⁃ Dewasa\r\n⁃ Orang tua\r\n\r\nDISARANKAN UNTUK :\r\n⁃ Cemilan nonton tv\r\n⁃ Main game\r\n⁃ Kumpul keluarga\r\n⁃ Kumpul teman, dll.\r\n(Pokok nya segala suasana\r\nbikin lbh seru deh kak)\r\n\r\nPROMO & BONUS :\r\n1. Disc 20%\r\n2. Beli lbh 5 pack dpt pot hrg\r\n4. Bonus supit/chopstick\r\n5. Bonus resep kekinian\r\n*WoW.. bnyk bgt promo & bonus nya\r\nYuk kak segera check out in\r\nJgn smp Kehabisan, krn terbatas !\r\n\r\nKOMPOSISI :\r\nAyam, terigu, sayuran, rempah, garam, bawang putih, minyak wijen\r\n(Semua bhn alami, bersih & sehat)\r\n\r\n~ DIMSUM DI PROSES\r\nMengikuti standar BPOM & MUI\r\njadi garansi aman di konsumsi\r\n~ DIMSUM DI KEMAS\r\nSudah matang & beku ya kak\r\n~ DIMSUM SEBELUM DI KIRIM\r\nTelah melewati standar kuality kontrol & seleksi yg ketat\r\n\r\nSARAN PENYIMPANAN :\r\n> Freezer (Beku) - 18’ = 2 bln\r\n> chiller/kulkas - 4’ = 7 hr\r\n> Suhu ruangan = 2 hr\r\n\r\nSARAN MEMASAK :\r\n> Kukus / Goreng / Grill = 5 - 10 mnt\r\n\r\nORDER & PENGIRIMAN :\r\na. Instan\r\n⁃ Order sebelum jam 15.00 WIB, dikirim di hari yg sama\r\n⁃ Pakai gosend estimasi sampai 1 hingga 2 jam\r\nb. Regular (free ongkir)\r\n⁃ Order sebelum jam 14.30 WIB, dikirim di hari yg sama\r\n⁃ Ekspedisi yg di pakai : J&T dan paxel\r\nc. Bisa kirim ke seluruh wil Indonesia, luar pulau Jawa harap chat CS kami ya kak!', '78.jpg', 'minuman');

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `full_name` varchar(255) NOT NULL,
  `user_name` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `status` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`id`, `full_name`, `user_name`, `password`, `status`) VALUES
(1, 'Diana', '3a23bb515e06d0e944ff916e79a7775c', '3a23bb515e06d0e944ff916e79a7775c', 'administrator'),
(2, 'Nola', 'f3d38a9b3c520cdf02917bb3ffd3405b', 'f3d38a9b3c520cdf02917bb3ffd3405b', 'employee'),
(3, 'Aurora', '99c8ef576f385bc322564d5694df6fc2', '99c8ef576f385bc322564d5694df6fc2', 'employee'),
(4, 'Fulan', '59ee8bd9e54c300ed35f1ead57cfdcf0', '59ee8bd9e54c300ed35f1ead57cfdcf0', 'customer'),
(5, 'a', '0cc175b9c0f1b6a831c399e269772661', '0cc175b9c0f1b6a831c399e269772661', 'customer'),
(6, 'b', '92eb5ffee6ae2fec3ad71c777531578f', '92eb5ffee6ae2fec3ad71c777531578f', 'customer'),
(7, 'c', '4a8a08f09d37b73795649038408b5f33', '4a8a08f09d37b73795649038408b5f33', 'customer');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `keranjang`
--
ALTER TABLE `keranjang`
  ADD PRIMARY KEY (`id_keranjang`);

--
-- Indexes for table `produk`
--
ALTER TABLE `produk`
  ADD PRIMARY KEY (`id`),
  ADD KEY `id` (`id`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `user_name` (`user_name`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `keranjang`
--
ALTER TABLE `keranjang`
  MODIFY `id_keranjang` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;

--
-- AUTO_INCREMENT for table `produk`
--
ALTER TABLE `produk`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=81;

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
